fix(search): reset query, page and sort on clear query
empathyco/x pull request #1045
Opened 2023-01-27 07:43 UTC by mnavarroespinosa

EX-7663

- Fixes issue that keeps the `page` param after clicking `Clear` query button in the search box. The same issue was happening with the `sort` parameter so I reset it too. 
- I opted for adding a new action `clearSearchParams` over using the existing `resetState` as the latter is only dispatched when requests are made and it's meant to evaluate the params that have changed between the old and new request. 
- Added an `e2e` regression test marked with `@regression` tag to facilitate identifying the regression tests.

2023-01-27 10:23 UTC, tiborux commented
It looks nice, but I was trying to find a way to not "hardcoding" the parameters that we want to clean. Right now, we are using the resetStateWire but it needs the request to check if should we clean the parameters, so I don't know if someone can find a better way to clean these parameters, in the past, we did the same but cleaning one by one the parameters.

2023-01-31 10:38 UTC, tajespasarela requested changes

2023-01-31 10:38 UTC, tajespasarela commented on packages/x-components/src/x-modules/search/store/actions/clear-search-params.action.ts
> +import { SearchXStoreModule } from '../types';
remove unnecessary action

2023-01-31 16:28 UTC, diegopf reviewed
This new approach seems that is not grouping changes properly when selecting filters now:

1. Scroll to page 2 (or beyond)
2. Select a filter
3. Two requests are made: one with the wrong page and another one with the page reset. The one with the wrong page is cancelled, but still we should avoid this.

2023-02-07 10:42 UTC, annacv commented on packages/x-components/src/x-modules/search/events.types.ts
> +   * @remarks The difference from `SearchRequestChanged` and this event is this one will be executed
```suggestion
   * @remarks The difference between `SearchRequestChanged` and this event is this one will be executed
```

2023-02-07 11:27 UTC, annacv commented
For me it's working fine

2023-02-07 15:15 UTC, mnavarroespinosa reviewed
Looks good to me!

2023-02-08 09:37 UTC, tiborux approved these changes

2023-02-08 10:55 UTC, tajespasarela approved these changes

2023-02-08 10:55 UTC, merged