docs(GitHub-project-landing): README update
empathyco/x pull request #106
Opened 2021-08-20 12:52 UTC by lydiafp

Revision of the GitHub **About this project** README to provide more detailed information and links to documentation.

## Motivation and Context ##

With the publication of the X repository as open source, the Project landing page has been revised to include links to documentation existing on the eDocs documentation and provide with sufficient details to understand the focus and scope of the project.

## Type of change ##

- Documentation update

## What is the destination branch of this PR? ##
 
main

## How Has This Been Tested? ##
N/A

## Checklist: ##

- [N/A ] My code follows the style guidelines of this project
- [N/A ] I have performed a self-review of my own code
- [N/A ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [N/A] My changes generate no new warnings
- [N/A] I have added tests that prove my fix is effective or that my feature works
- [N/A] New and existing unit tests pass locally with my changes

2021-08-23 09:28 UTC, herrardo commented
Let's see the @tajespasarela opinion, but i think that:

- `all_popular_next_searches.gif` should be renamed to something like: `x-components-demo.gif`
- the folder to store this file should be `/assets` inside the root folder, `.github` doesn't seem the best place

2021-08-23 10:41 UTC, herrardo requested changes
Let's see the @tajespasarela opinion, but i think that:

- `all_popular_next_searches.gif` should be renamed to something like: `x-components-demo.gif`
- the folder to store this file should be `/assets` inside the root folder, `.github` doesn't seem the best place

2021-08-30 20:52 UTC, herrardo approved these changes

2021-08-31 07:39 UTC, tajespasarela approved these changes

2021-08-31 07:40 UTC, merged