Create Renderless extra param component
empathyco/x pull request #107
Opened 2021-08-23 06:45 UTC by pmareke

EX-4605

2021-08-23 11:18 UTC, davidmfempathy requested changes

2021-08-23 12:09 UTC, javieri-empathy requested changes

2021-08-23 12:09 UTC, javieri-empathy commented on packages/x-components/src/x-modules/extra-params/components/__tests__/renderless-extra-params.spec.ts
> +          <template #search="{ defaultValue, updateValue }">
I don't know how this is working, you are defining a scoped slot that has a scoped slot named `search` 🤣,  For me it is far more clear if we just use the template like in other tests. Here I have exactly the input of the test, properly defined, a template with a default scoped slot.

```ts
    const { wrapper } = renderRenderlessExtraParams({
      extraParamName: 'warehouse',
      template: `
        <RenderlessExtraParam #default="{ defaultValue, updateValue }">
          <button data-test="custom-slot" @click="updateValue(45678)">Update warehouse</button>
        </RenderlessExtraParam>`
    });

```

 Moreover, wasn't that scoped slots property giving us some troubles?

```
    const { wrapper } = renderRenderlessExtraParams({
      extraParamName: 'warehouse',
      template: `
        <RenderlessExtraParam #default="{ defaultValue, updateValue }">
          <button data-test="custom-slot" @click="updateValue(45678)">Update warehouse</button>
        </RenderlessExtraParam>`
    });
```

2021-08-23 13:44 UTC, pmareke commented on packages/x-components/src/x-modules/extra-params/components/renderless-extra-param.vue
> +    syncUpdateValue(newValue: unknown): void {
It'll change if you change the prop sent to the component right?

2021-08-24 05:20 UTC, pmareke commented on packages/x-components/src/x-modules/extra-params/components/__tests__/extra-params.spec.ts
> -    expect(extraParamsProvidedCallback).toHaveBeenCalledTimes(2);
My fault, I asume that `toHaveBeenNthCalledWith` was the combination of `toHaveBeenCalledWith` and `toHaveBeenCalledTimes`, but it's not.

2021-08-24 07:42 UTC, guillei10 submitted a review, later dismissed

2021-08-24 07:56 UTC, davidmfempathy approved these changes

2021-08-24 07:56 UTC, davidmfempathy commented on packages/x-components/src/x-modules/extra-params/components/__tests__/renderless-extra-params.spec.ts
> +  it("not emits ExtraParamsProvided event when the component receives a default value if it's in the store", () => {
doesn't emit

2021-08-24 08:02 UTC, guillei10 approved these changes

2021-08-24 08:03 UTC, davidmfempathy approved these changes

2021-08-24 08:19 UTC, merged