feat(components): add  `columns` prop in BaseVariableColumnGrid
empathyco/x pull request #1112
Opened 2023-03-22 08:56 UTC by tiborux

EX-8135

2023-03-22 12:43 UTC, LuisMartinez15 approved these changes
👏🏿 good job 👏🏿

2023-03-22 14:10 UTC, CachedaCodes requested changes
gj!

2023-03-22 14:10 UTC, CachedaCodes commented on packages/x-components/src/components/base-variable-column-grid.vue
> +     * The number of columns to render in the grid.
`columns` and `columnsToRender` have almost the same description.

2023-03-22 14:10 UTC, CachedaCodes commented on packages/x-components/src/components/base-variable-column-grid.vue
> +     * The number of columns provided by the user.
Can we change to `provided by a user interaction`? For me, it's clearer that way

2023-03-23 07:41 UTC, tajespasarela requested changes

2023-03-23 07:41 UTC, tajespasarela commented on packages/x-components/src/components/base-variable-column-grid.vue
> +    protected providedColumns = 0;
We are going to need to provide 0 columns too as is for "automatic" columns number. So no provided columns should be null.

```suggestion
    protected providedColumns: number | null = null;
```

2023-03-23 07:41 UTC, tajespasarela commented on packages/x-components/src/components/base-variable-column-grid.vue
> +      return this.providedColumns || this.columns;
```suggestion
      return this.providedColumns === null?  this.columns: this.providedColumns;
```

2023-03-23 10:11 UTC, CachedaCodes approved these changes

2023-03-23 10:12 UTC, tajespasarela approved these changes

2023-03-23 10:13 UTC, merged