feat(design-system): add simple filter variant
empathyco/x pull request #1127
Opened 2023-04-11 08:33 UTC by ajperezbau

EMP-311

2023-04-11 13:01 UTC, diegopf commented on packages/x-tailwindcss/src/x-tailwind-plugin/components/facet-filter/simple.ts
> +        color: theme('colors.neutral.90'),
Currently every simple filter looks the same regardless if they have a color variant added. It is only when you select the filter then you can see something different. Is this behaviour intended?

2023-04-11 13:06 UTC, diegopf commented on packages/x-tailwindcss/demo/src/components/xds-facet-filter.vue
I would add at least one combination with the simple filter

2023-04-12 08:31 UTC, mnavarroespinosa requested changes

2023-04-12 08:31 UTC, mnavarroespinosa commented on packages/x-tailwindcss/demo/src/components/xds-facet-filter.vue
> +          addParentClasses(this.base)(this.simple)
What do you think of adding the `underline` and the `selected` variants too?

```suggestion
          addParentClasses(this.base, this.selected)(this.ghost),
          addParentClasses(this.base)(this.simple),
          addParentClasses(this.base, this.selected)(this.simple),
          addParentClasses(this.base)(this.underline),
          addParentClasses(this.base, this.selected)(this.underline)
```

Testing this change, I noticed the `disabled` styles are not properly applied on `hover` for the `underline` and the `simple+selected` variants:

![image](https://user-images.githubusercontent.com/77450928/231399394-c84b24c0-4ff3-465a-b464-775fa4c7ed15.png)

2023-04-12 10:44 UTC, ajperezbau commented on packages/x-tailwindcss/src/x-tailwind-plugin/theme.ts
> +    xs: '-0.025em',
Yep, it was wrong

2023-04-12 10:53 UTC, ajperezbau commented on packages/x-tailwindcss/src/x-tailwind-plugin/components/facet-filter/simple.ts
> +          color: `var(--filter-color-50, ${theme('colors.neutral.50')})`
Yep, It was outdated.
Cris just updated the designs to change it to `color-50`.

2023-04-13 06:57 UTC, mnavarroespinosa approved these changes

2023-04-13 07:25 UTC, diegopf approved these changes

2023-04-13 07:26 UTC, merged