feat (design-system): deprecate old DS list component
empathyco/x pull request #1134
Opened 2023-04-13 15:13 UTC by ajperezbau

EMP-133

2023-04-14 08:42 UTC, mnavarroespinosa commented on packages/x-components/src/components/panels/base-tabs-panel.vue
> +    tabListClass="x-flex-col"
I guess this should be `x-flox-row` but it collides with `x-flex x-flex-col` added in line 5.
```suggestion
    tabListClass="x-flex-row"
```

2023-04-18 07:15 UTC, diegopf requested changes

2023-04-18 07:15 UTC, diegopf commented on packages/x-components/src/components/suggestions/base-suggestions.vue
> +    &,
```suggestion
```

2023-04-18 07:29 UTC, mnavarroespinosa approved these changes

2023-04-18 07:31 UTC, merged