feat: add `filterItemClass` prop to `HierarchicalFilter`
empathyco/x pull request #1135
Opened 2023-04-14 06:30 UTC by diegopf

EMP-120

Adds a new dynamic prop to be able to style the filter element itself.

2023-04-14 08:32 UTC, tiborux commented on packages/x-components/src/x-modules/facets/components/filters/hierarchical-filter.vue
> +          :class="[cssClasses, filterItemClass]"
should we expose this class in the slot?

2023-04-14 09:01 UTC, tiborux approved these changes

2023-04-14 09:01 UTC, tiborux commented
gj

2023-04-14 09:01 UTC, tiborux commented
<img src="https://media0.giphy.com/media/IoUFBJwKswTVZbSfhl/giphy.gif"/>

2023-04-14 09:28 UTC, mnavarroespinosa requested changes

2023-04-14 09:28 UTC, mnavarroespinosa commented on packages/x-components/src/x-modules/facets/components/filters/hierarchical-filter.vue
> +      dynamicPropsMixin(['childrenFiltersClass', 'filterItemClass'])
Could you add the new property `filterItemClass` to the docs below?

2023-04-17 06:46 UTC, mnavarroespinosa approved these changes

2023-04-17 06:58 UTC, tiborux approved these changes

2023-04-17 06:58 UTC, merged