feat: migrate modals to vue 3 syntax
empathyco/x pull request #1141
Opened 2023-04-18 07:41 UTC by lauramargar

EMP-30

2023-04-19 07:09 UTC, tiborux commented on packages/x-components/src/components/modals/base-events-modal-open.vue
> +      const events = computed<Partial<XEventsTypes>>(() => {
We can reduce this to:

```
const events = computed<Partial<XEventsTypes>>(() => ({ [props.openingEvent]: undefined }));
```

But up to you.

2023-04-19 07:13 UTC, tiborux commented on packages/x-components/src/components/modals/base-events-modal-close.vue
> +    /**
Move this documentation up, before the `defineComponent`

2023-04-19 07:13 UTC, tiborux commented on packages/x-components/src/components/modals/base-events-modal-open.vue
> +    /**
Move this documentation up, before the defineComponent

2023-04-19 07:13 UTC, tiborux commented on packages/x-components/src/components/modals/base-id-modal-close.vue
> +     * Component that allows to close a modal by emitting
Move this documentation up, before the defineComponent

2023-04-19 07:13 UTC, tiborux commented on packages/x-components/src/components/modals/base-id-modal-open.vue
> +     * Component that allows to open a modal by emitting {@link XEventsTypes.UserClickedOpenModal}
Move this documentation up, before the defineComponent

2023-04-19 07:14 UTC, tiborux commented on packages/x-components/src/components/modals/close-main-modal.vue
>      /**
Move this documentation up, before the defineComponent

2023-04-19 07:14 UTC, tiborux commented on packages/x-components/src/components/modals/base-events-modal-open.vue
> +      openingEvent: {
We can add documentation about this prop.

2023-04-19 07:17 UTC, tiborux commented on packages/x-components/src/components/modals/close-main-modal.vue
> +  export default defineComponent({
We can add documentation here about what it does the component.

2023-04-19 07:17 UTC, tiborux commented on packages/x-components/src/components/modals/main-modal.vue
> +  export default defineComponent({
We can add documentation here about what it does the component.

2023-04-19 07:19 UTC, tiborux commented on packages/x-components/src/components/modals/open-main-modal.vue
> +  export default defineComponent({
We can add documentation here about what it does the component.

2023-04-24 11:55 UTC, CachedaCodes requested changes
gj!

2023-04-24 11:55 UTC, CachedaCodes commented on packages/x-components/src/components/modals/base-events-modal-close.vue
> +      });
This can be simplified to:

```suggestion
      const events = computed<Partial<XEventsTypes>>(() => ({ [props.closingEvent]: undefined }));
```

2023-04-24 11:55 UTC, CachedaCodes commented on packages/x-components/src/components/modals/main-modal.vue
> +      /**
```suggestion
      const openEvents: XEvent[] = ['UserClickedOpenX', 'UserOpenXProgrammatically'];
      
      /**
```

2023-04-24 11:55 UTC, CachedaCodes commented on packages/x-components/src/components/modals/base-id-modal-open.vue
> +      /**
```suggestion
      const $x = use$x();
      
      /**
```

2023-04-24 11:55 UTC, CachedaCodes commented on packages/x-components/src/components/modals/base-id-modal-close.vue
> +      /**
```suggestion
      const $x = use$x();
      
      /**
```

2023-04-26 07:11 UTC, CachedaCodes requested changes

2023-04-26 07:11 UTC, CachedaCodes commented on packages/x-components/src/components/modals/main-modal.vue
> +        type: [Vue, String]
Create a new file in `x-components/src/utils/options-api.ts` and export there the value we'll use for the animation props across the project. Something like 
````typescript
export const animationProp = [String, Object, Function] as PropType<[DefineComponent | string]>;
````

Then use it here.

2023-04-28 08:16 UTC, CachedaCodes submitted a review, later dismissed

2023-05-03 07:08 UTC, tiborux commented on packages/x-components/src/utils/options-api.ts
> +export const animationProp = [String, Object, Function] as PropType<DefineComponent | string>;
I will move it to the types folder and rename it to: `AnimationProp`

2023-05-03 10:34 UTC, tiborux approved these changes

2023-05-03 10:35 UTC, merged