feat: migrate filters to vue 3 syntax
empathyco/x pull request #1144
Opened 2023-04-18 10:24 UTC by lauramargar

EMP-426

2023-04-25 09:12 UTC, CachedaCodes requested changes

2023-04-25 09:12 UTC, CachedaCodes commented on packages/x-components/src/components/filters/labels/__tests__/base-price-label.spec.ts
> +    ':less-than="lessThan" :from="from" :from-to="fromTo" />'
We're not modifying the template in any test, so you can move this inside the `mount` directly and remove it from the parameters.

2023-04-27 13:40 UTC, CachedaCodes requested changes

2023-04-27 13:40 UTC, CachedaCodes commented on packages/x-components/src/components/filters/labels/__tests__/base-price-label.spec.ts
> +        ':less-than="lessThan" :from="from" :from-to="fromTo" />'
```suggestion
        `<BasePriceFilterLabel :filter="filter" :format="format" 
        :less-than="lessThan" :from="from" :from-to="fromTo" />`
```

2023-05-01 08:17 UTC, CachedaCodes approved these changes

2023-05-03 12:52 UTC, tiborux approved these changes

2023-05-03 12:53 UTC, merged