feat: migrate results to vue 3 syntax
empathyco/x pull request #1145
Opened 2023-04-18 10:58 UTC by lauramargar

EMP-427

2023-04-26 09:25 UTC, CachedaCodes requested changes

2023-04-26 13:53 UTC, support-empathy commented
This is a link to Empathy Platform Docs Portal preview in a development environment. 
 ⚠️ Only for Empathy members. We’re sorry for the inconvenience!
 [Check out EPDocs preview](https://docs-dev.empathy.co/preview/x-1145/index.html)

2023-04-27 14:11 UTC, support-empathy commented
This is a link to Empathy Platform Docs Portal preview in a development environment. 
 ⚠️ Only for Empathy members. We’re sorry for the inconvenience!
 [Check out EPDocs preview](https://docs-dev.empathy.co/preview/x-1145/index.html)

2023-04-28 08:07 UTC, CachedaCodes requested changes

2023-04-28 08:07 UTC, CachedaCodes commented on packages/x-components/src/components/result/base-result-rating.vue
> +    ref="root"
For consistency, keep the same name for the refs of the root element. Here we use `root` and in other component `el`, should be the same in both (I prefer `el` but it's your call).

2023-05-01 08:18 UTC, CachedaCodes approved these changes

2023-05-02 08:04 UTC, CachedaCodes requested changes

2023-05-02 08:04 UTC, CachedaCodes commented on packages/x-components/src/components/result/base-result-image.vue
> +      const resultImages = ref(props.result.images!);
This breaks the reactivity of the images, use this instead:

```suggestion
      const resultImages = toRef(props.result, 'images');
```

2023-05-02 12:36 UTC, CachedaCodes approved these changes

2023-05-04 10:23 UTC, diegopf approved these changes

2023-05-04 10:27 UTC, merged