feat: migrate panels components to vue 3 syntax
empathyco/x pull request #1150
Opened 2023-04-19 13:22 UTC by lauramargar

EMP-424

2023-04-24 14:00 UTC, CachedaCodes requested changes

2023-04-24 14:00 UTC, CachedaCodes commented on packages/x-components/src/components/panels/__tests__/base-header-toggle-panel.spec.ts
> +    wrapper.vm.$nextTick();
For me, the tests pass without this line. If this is here for something that I can't replicate, then remove the `await` in the line 89 and put it here instead.

2023-04-26 07:12 UTC, CachedaCodes requested changes

2023-04-26 07:12 UTC, CachedaCodes commented on packages/x-components/src/components/panels/base-toggle-panel.vue
> +        type: [String, Object, Function] as PropType<string | DefineComponent>,
Use here the value you created in [EMP-30](https://searchbroker.atlassian.net/browse/EMP-30)

2023-04-26 07:12 UTC, CachedaCodes commented on packages/x-components/src/components/panels/base-header-toggle-panel.vue
> +        type: [String, Object, Function] as PropType<string | DefineComponent>,
Use here the value you created in [EMP-30](https://searchbroker.atlassian.net/browse/EMP-30)

2023-04-28 08:03 UTC, CachedaCodes submitted a review, later dismissed

2023-05-03 07:13 UTC, tiborux commented on packages/x-components/src/utils/options-api.ts
> +import { DefineComponent, PropType } from 'vue';
As I said in the other PR, maybe it should be in the types folder and rename it to `AnimationProp`

2023-05-03 12:41 UTC, tiborux approved these changes

2023-05-03 12:42 UTC, merged