feat(design-system): deprecate old DS remaining styles and components
empathyco/x pull request #1154
Opened 2023-04-21 07:27 UTC by ajperezbau

EMP-133

2023-04-21 08:23 UTC, mnavarroespinosa approved these changes

2023-04-24 07:09 UTC, diegopf requested changes

2023-04-24 07:09 UTC, diegopf commented on packages/x-components/build/build.ts
>      await bundleCssDepracatedComponents.write(cssDeprecatedComponentsRollupConfig.output);
```suggestion
    const bundleCssDeprecatedComponents = await rollup(cssDeprecatedComponentsRollupConfig);
    await bundleCssDeprecatedComponents.write(cssDeprecatedComponentsRollupConfig.output);
```

2023-04-24 09:32 UTC, diegopf approved these changes

2023-04-24 10:18 UTC, merged