feat: migrate suggestions and currency components to vue 3 syntax
empathyco/x pull request #1159
Opened 2023-04-25 07:03 UTC by lauramargar

EMP-529

2023-04-26 09:45 UTC, CachedaCodes requested changes
gj!

2023-04-26 09:45 UTC, CachedaCodes commented on packages/x-components/src/components/currency/base-currency.vue
> +    setup(props) {
Add linebreaks between variables.

2023-04-26 09:45 UTC, CachedaCodes commented on packages/x-components/src/components/currency/base-currency.vue
> +      });
Simplify to

```suggestion
      const currency = computed<string>(() => currencyFormatter(props.value, renderedFormat.value));
```

2023-04-26 09:45 UTC, CachedaCodes commented on packages/x-components/src/components/suggestions/base-suggestion.vue
> +        required: false
Not needed because it's the default behavior.

2023-04-26 09:45 UTC, CachedaCodes commented on packages/x-components/src/components/suggestions/base-suggestion.vue
> +        default: false
Not needed because it's the default behavior.

2023-04-26 09:45 UTC, CachedaCodes commented on packages/x-components/src/components/suggestions/base-suggestion.vue
> +      const root = ref<HTMLElement | null>(null);
Add docs for this.

2023-04-26 09:45 UTC, CachedaCodes commented on packages/x-components/src/components/suggestions/base-suggestion.vue
> +    setup(props) {
Add line breaks here too.

2023-04-26 09:45 UTC, CachedaCodes commented on packages/x-components/src/components/suggestions/base-suggestion.vue
> +      });
Simplify to 

```suggestion
      const filter = computed<BooleanFilter | undefined>(
        () => props.suggestion.facets?.[0]?.filters[0] as BooleanFilter
      )
```

2023-04-26 09:45 UTC, CachedaCodes commented on packages/x-components/src/components/suggestions/base-suggestion.vue
> +      });
Simplify to

```suggestion
      const shouldHighlightCurated = computed<boolean>(
        () => props.highlightCurated && !!props.suggestion.isCurated
      )
```

2023-04-26 09:45 UTC, CachedaCodes commented on packages/x-components/src/components/suggestions/base-suggestion.vue
>        });
Simplify to

```suggestion
      const dynamicCSSClasses = computed<VueCSSClasses>(() => ({
        'x-suggestion--is-curated': shouldHighlightCurated.value
      }));
```

2023-04-26 09:45 UTC, CachedaCodes commented on packages/x-components/src/components/suggestions/__tests__/base-suggestion.spec.ts
> +  template = '<BaseSuggestion :query="query" :suggestion="suggestion" ' +
We're always using the same template across all tests, so you can set it inside the function

2023-04-28 08:11 UTC, CachedaCodes requested changes

2023-04-28 08:11 UTC, CachedaCodes commented on packages/x-components/src/components/suggestions/base-suggestion.vue
> +      const root = ref<HTMLElement | null>(null);
Keep consistency with the decided name of the other PR (either `root` or `el` here)

2023-05-01 08:20 UTC, CachedaCodes approved these changes

2023-05-04 10:48 UTC, diegopf approved these changes

2023-05-04 10:49 UTC, merged