feat(semantic-queries): add maxItemsToRequest config
empathyco/x pull request #1224
Opened 2023-06-01 15:09 UTC by ajperezbau

EMP-934

## Motivation and context

Add a configuration to the `SemanticQueries` module to be able to limit the number of semantic queries to request.

- [ ] Dependencies. If any, specify:
- [ ] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [x] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [x] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [x] I have performed a **self-review** on my own code.
- [x] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [x] My changes generate **no new warnings**.
- [x] I have added **tests** that prove my fix is effective or that my feature works.
- [x] New and existing **unit tests pass locally** with my changes.

2023-06-02 06:55 UTC, annacv commented on packages/x-components/src/x-modules/semantic-queries/store/__tests__/getters.spec.ts
> +    it('contains the query if the totalResults is equal than the threshold', () => {
```suggestion
    it('contains the query if the totalResults are equal than the threshold', () => {
```

2023-06-02 06:57 UTC, annacv commented on packages/x-components/src/x-modules/semantic-queries/store/__tests__/getters.spec.ts
> +    it('is null if there is no query or the totalResults is higher than the threshold', () => {
```suggestion
    it('is null if there is no query or the totalResults are higher than the threshold', () => {
```

2023-06-05 13:39 UTC, CachedaCodes requested changes
gj 👍

2023-06-05 13:39 UTC, CachedaCodes commented on packages/x-components/src/x-modules/semantic-queries/store/getters/request.getter.ts
Remove the `@param getters` of the JSDocs.

2023-06-06 06:26 UTC, annacv approved these changes
🎉

2023-06-06 07:32 UTC, CachedaCodes approved these changes

2023-06-06 07:32 UTC, merged