feat(queries-preview): add isAnyQueryLoadedInPreview composable
empathyco/x pull request #1229
Opened 2023-06-07 14:57 UTC by ajperezbau

EMP-1006

## Motivation and context

Add composable to check if any query passed to it is loaded in the query preview module.

- [ ] Dependencies. If any, specify:
- [ ] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [ ] `Main`
- [x] Other. Specify: [feature/EMP-1006](https://github.com/empathyco/x/tree/feature/EMP-1006)

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [x] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [x] I have performed a **self-review** on my own code.
- [x] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [x] My changes generate **no new warnings**.
- [x] I have added **tests** that prove my fix is effective or that my feature works.
- [x] New and existing **unit tests pass locally** with my changes.

2023-06-07 15:12 UTC, annacv commented on packages/x-components/src/x-modules/queries-preview/composables/use-queries-preview.composable.ts
> +   */
This doc is from the code below 👀

2023-06-07 15:13 UTC, annacv commented on packages/x-components/src/x-modules/queries-preview/composables/use-queries-preview.composable.ts
> +   * @returns True if some query has results.
```suggestion
   * Indicates if any of the queries previews have results.
```

2023-06-07 15:19 UTC, annacv commented on packages/x-components/src/x-modules/queries-preview/composables/__tests__/use-queries-preview.composable.spec.ts
> +    });
Although it is a bit redundant, maybe we can split this in two tests and handle the noResults use case, too. But, up to you:
```suggestion
    it('returns true if any query has results', () => {
      resetXQueriesPreviewStateWith(store, {
        queriesPreview: {
          queryWithResults: createQueryPreviewItem('queryWithResults'),
          queryWithNoResults: createQueryPreviewItem('queryWithNoResults', {
            totalResults: 0,
            results: []
          })
        }
      });
      expect(isAnyQueryLoadedInPreview(['queryWithResults'])).toBe(true);
    });
    
     it('returns false if any query has no results', () => {
      resetXQueriesPreviewStateWith(store, {
        queriesPreview: {
          queryWithNoResults: createQueryPreviewItem('queryWithNoResults', {
            totalResults: 0,
            results: []
          })
        }
      });
      expect(isAnyQueryLoadedInPreview(['queryWithNoResults'])).toBe(false);
    });
```

2023-06-08 14:46 UTC, annacv submitted a review, later dismissed
🎉

2023-06-13 09:03 UTC, CachedaCodes requested changes

2023-06-13 09:03 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/composables/__tests__/use-queries-preview.composable.spec.ts
> +  };
Might be a good idea to make this a stub generator like the ones we have for results, NQ, etc, maybe move the `getQueryPreviewRequest` function there too.

2023-06-13 14:07 UTC, CachedaCodes submitted a review, later dismissed

2023-06-14 06:46 UTC, CachedaCodes approved these changes

2023-06-14 06:46 UTC, merged