Fix/emp 1228 editable number range filter
empathyco/x pull request #1243
Opened 2023-07-04 07:56 UTC by annacv

[EMP-1228](https://searchbroker.atlassian.net/browse/EMP-1228)

## Motivation and context
Make this filter unique, so only one range is applied if we set some ranges consecutively.

- [ ] Dependencies. If any, specify:
- [x] Open issue. If applicable, link:

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [x] Change requires a documentation update

## What is the destination branch of this PR?
- [x] `Main`
- [ ] Other. Specify:

## How has this been tested?
- Setting a range and editing it: it should only show one filter as selected.
- Setting a range and also selecting other filters: clicking the clear filters button should remove them all from the selected filters list.
- Setting a range and deselecting it by clicking on it: the filter should be removed from the selected filters list.

2023-07-04 08:01 UTC, annacv commented on packages/x-components/src/views/home/aside.vue
> +            {{ filter.label ?? filter.id }}
The id is set as an alternative label. If the min/max range were used, when the page is reloaded or we perform another search, the filter's getter won't keep that values as the filter model changes to a RawFilter.

2023-07-07 08:43 UTC, mavmaf requested changes
Please take a look to the aside menu: the range is added to filters which I believe don't belongs to (brand one, for instance). 
Also, with current code, simple-filters E2E fails 🤔 
![image](https://github.com/empathyco/x/assets/77147901/bb357284-84d1-4732-af8b-0bce9b38285a)

2023-07-10 10:03 UTC, CachedaCodes requested changes
gj!

2023-07-24 11:08 UTC, lauramargar submitted a review, later dismissed
🎉

2023-07-24 11:10 UTC, lauramargar approved these changes

2023-07-24 13:08 UTC, mavmaf approved these changes

2023-07-25 07:40 UTC, annacv reviewed
Hi! Good job!!!

I have been testing and found a use case where the `RangeFilter` behaves differently than other filters when we reload the page. This could be held in another task: 

- Test 1 --> [Hierarchical Filter Test](http://localhost:8080/?filter=promotion%3Ablack%20friday&q=bolso&scroll=195890681): Select a Hierarchical Filter and reload the page, filter is kept in the URL and the results view is rendered with the filter selected
- Test 2 --> [Number Range Filter Test](http://localhost:8080/?filter=price%3A0-10&q=bolso): Select a Number Range Filter and reload the page, filter is kept in the URL, but the results view is not loaded
- Test 3 --> [Editable Number Range Filter Test](http://localhost:8080/?filter=salePrice%3A1-200&q=collar): Select an Editable Number Range Filter and reload the page, filter is kept in the URL and the results view is kept with the filter selected
- Test 4 --> [Hierarchical + Editable Number Range test](http://localhost:8080/?filter=promotion%3Arebajas&filter=salePrice%3A2-200&q=collar): Select Select a Hierarchical Filter and an Editable Number Range Filter and reload the page, filters are kept in the URL and the results view is rendered with the filters selected
- Test 5 --> [Several filter types test](http://localhost:8080/?filter=promotion%3Arebajas&filter=price%3A0-10&filter=salePrice%3A2-200&q=collar): Select Select a Hierarchical Filter, a Number Range Filter, and an Editable Number Range Filter and reload the page, filters are kept in the URL, but the results view is not loaded

2023-07-25 12:22 UTC, merged