Support max-len in Vue components
empathyco/x pull request #1272
Opened 2023-08-30 13:30 UTC by annacv

[EMP-1908](https://searchbroker.atlassian.net/browse/EMP-1908)

resolves #1063
[Ref issue](https://github.com/empathyco/x/issues/1063)

TEST
1- [Here](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/max-len.md#ignorestrings-true) are some examples for testing `ignoreUrls`, `ignoreStrings`, `ignoreTemplateLiterals` rules, that can be applied in, for example, `Home.vue`

2- Run eslint in your project:
run `build eslint-plugin-x`
run `pnpm install —frozen-lockfile` in x-components
run `npm run lint`  and check:
- It should ignore long urls in vue files
- It should ignore long classes, for example line 331 in Home.vue
- It should ignore icon files as ‘user-filled.vue’

[EMP-1908]: https://searchbroker.atlassian.net/browse/EMP-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-08-30 15:18 UTC, herrardo requested changes
I think the proposal in the issue was correct, it was to add this configuration to the `eslint-plugin-x` config, so everybody using that package would be using the new rules.

That would mean to add it here:

https://github.com/empathyco/x/blob/main/packages/eslint-plugin-x/lib/configs/eslint.js

2023-08-31 13:04 UTC, annacv commented on packages/eslint-plugin-x/lib/configs/eslint.js
> +              ignorePattern: '|class=".*"$ |https://github',
This `ignorePattern` config was previously set in [x-components' eslint config](https://github.com/empathyco/x/blob/main/packages/x-components/.eslintrc.js#L22).

2023-08-31 13:07 UTC, annacv commented on packages/x-components/.eslintrc.js
> -    },
As we are disabling the entire `max-len` rule for vue components, in order to use` vue/max-len` one, we get rid of this config here.

2023-09-01 06:59 UTC, annacv commented on packages/x-components/.eslintrc.js
>        }
This is the only way I found to effectively disable `max-len`, I tried in eslint-x plugin file but it didn't have effect

2023-09-01 08:46 UTC, annacv commented
This config seems not to be working properly

2023-09-01 08:46 UTC, closed without merging