feat(scroll): add top offset when automatically scrolling to main-scroll-item
empathyco/x pull request #1277
Opened 2023-09-11 14:03 UTC by CachedaCodes

[EMP-2021](https://searchbroker.atlassian.net/browse/EMP-2021)

## Motivation and context
Depending on the setup's header it was possible that, when automatically scrolling to an element in the main scroll, the element was cut by the header. This feature adds a prop to the main-scroll-item to add an offset to the scrolling.

- [ ] Dependencies. If any, specify:
- [X] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [X] `Main`
- [ ] Other. Specify:

## How has this been tested?
Set the prop and reload a url that has `scroll` attribute.

[EMP-2021]: https://searchbroker.atlassian.net/browse/EMP-2021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-09-11 20:43 UTC, herrardo reviewed
I was curious about this and started testing it, but I can't do what I want, it might be some kind of uselessness on my end, but I would like to check it together.

2023-09-12 07:14 UTC, lauramargar reviewed
I have tried to test it on the archetype and it seems like the element to scroll is always at the bottom. Maybe we can check it together.

2023-09-13 06:57 UTC, lauramargar commented
It works perfectly with the regular results (`result` component), but I have tried to reload the page with a result of `CustomNextQueriesPreview` and it doesn't work. I have talked with @CachedaCodes and we found that the problem is an `overflow: hidden` in the sliding panel of the `CustomNextQueriesPreview` component.

2023-09-13 11:01 UTC, herrardo requested changes

2023-09-13 11:01 UTC, herrardo commented on packages/x-components/src/x-modules/scroll/components/main-scroll-item.vue
> +          this.$el.scrollIntoView();
```suggestion
          this.$el.scrollIntoView({block: 'center'})
```

After doing some testing, this seems a good option. This option centers always the item in the viewport, so we would have some part of the previous row visible, but the specified item will be always in the view port.

Downside: We would have to modify some test probably.

2023-09-14 11:28 UTC, lauramargar approved these changes

2023-09-15 07:03 UTC, merged