feat: add filters to the query preview request
empathyco/x pull request #1292
Opened 2023-09-19 06:40 UTC by lauramargar

# Pull request template
 
Currently, the query preview component accept 2 params, title&query, so it creates it retrieves the products and show them in a viz, an sliding panel as default.

It would be great if we could add filters & extra params to the search request, now extra params are developed, so we also have to add filters. These params could help to narrow the results, that could be very interesting for some customers.

## Motivation and context

- [ ] Dependencies. If any, specify:
- [X] Open issue. If applicable, link: [EMP-2141](https://searchbroker.atlassian.net/browse/EMP-2141)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [X] `Main`
- [ ] Other. Specify:

## How has this been tested?

At `Home.vue` file add or remove filters in `queriesPreviewInfo` var. The carrousels of query preview should be filtered.

2023-09-19 13:42 UTC, herrardo commented on packages/x-components/src/views/home/Home.vue
> +        filters: ['categoryIds:5b612edb5', 'fit:regular']
I would change the example to see it work as a real example:

```suggestion
        query: 'summer dress',
        filters: ['categoryIds:5b612edb5', 'brand:marni']
```

2023-09-19 13:46 UTC, CachedaCodes requested changes

2023-09-19 13:46 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/components/query-preview.vue
> +        return filtersList;
Add space here for clarity.

```suggestion

        return filtersList;
```

2023-09-19 13:46 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/components/query-preview.vue
> +      const filtersApply = this.queryPreviewInfo.filters?.reduce((filtersList, filterId) => {
```suggestion
      const filters = this.queryPreviewInfo.filters?.reduce((filtersList, filterId) => {
```

2023-09-19 13:46 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/components/query-preview.vue
> +        filters: filtersApply,
```suggestion
        filters,
```

2023-09-19 13:46 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/components/query-preview.vue
>        return {
Add space here for clarity.

```suggestion

      return {
```

2023-09-19 13:46 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/components/query-preview.vue
In this component's test 'sends the `QueryPreviewRequestUpdated` event' add filters to the `queryPreviewInfo` and check that the `queryPreviewRequest` has them.

2023-09-20 09:41 UTC, CachedaCodes approved these changes

2023-09-20 09:41 UTC, merged