ci: add release alpha action
empathyco/x pull request #13
Opened 2021-05-17 09:29 UTC by javieri-empathy

EX-3911

# Pull Request Template #

Adds a new manual action to release an alpha version, and removes the alpha related logic from the prepare-release action.

## Motivation and Context ##

The idea is to be able to release alphas fast without having to rely on teammates. For a stable version we still have to review a PR and probably fix the change-log.

## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## What is the destination branch of this PR? ##

`main`

## How Has This Been Tested? ##

In the [lerna playground mono-repo](https://github.com/javieri-empathy/lerna-repo)

## Checklist: ##

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-17 09:45 UTC, pmareke commented on .github/workflows/prepare-release.yml
> -          token: ${{ secrets.SUPPORT_TOKEN }}
Why did you remove this line? Please revert this change.

2021-05-17 12:04 UTC, tajespasarela requested changes
![image](https://user-images.githubusercontent.com/5759712/118485390-adecaf80-b718-11eb-8a94-bb67021aae69.png)
I got that error on the release, but after that I couldn't see the error anymore

2021-05-17 12:28 UTC, javieri-empathy commented
> ![image](https://user-images.githubusercontent.com/5759712/118485390-adecaf80-b718-11eb-8a94-bb67021aae69.png)
> I got that error on the release, but after that I couldn't see the error anymore

I can't find any info about it. It might be an issue of github.com trying to display the log of that step before actually having receiving them?

2021-05-17 12:52 UTC, tajespasarela approved these changes

2021-05-18 05:28 UTC, pmareke approved these changes

2021-05-18 05:29 UTC, merged