feat(search): add origin to the request
empathyco/x pull request #130
Opened 2021-09-01 10:52 UTC by tiborux

# Pull Request Template #

This pr adds the origin in the searchRequest.

## Motivation and Context ##

This pr is needed to emit the origin in every request. To achieve this, we had to change the wireDispatch and commit to adding the metadata on them because right now every events send a new parameter that its the metaData and we have to recover it from these events using the wiring.

## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ##

Just search something and check how the origin changes, as the origin is default always, you can set a breakpoint in the mutation to check that it's called every time that you search for a query.

2021-09-01 12:45 UTC, davidmfempathy requested changes

2021-09-01 12:45 UTC, davidmfempathy commented on packages/x-components/src/store/store.types.ts
> + * State and Getters Store type for {@link RootXStoreState} and payload and metadata types.
The link is wrong as it has to be `RootStoreStateAndGetters` but I'd put I'd write its purpose instead of what it has in the interface.

2021-09-01 12:45 UTC, davidmfempathy commented on packages/x-components/src/store/store.types.ts
> + * Type safe which allows the access to the State, the Getters,the payload and metadata of
space after the ,

2021-09-01 12:45 UTC, davidmfempathy commented on packages/x-components/src/x-modules/search/store/types.ts
> +  /** The origin property of the request. */
can we remove it ?

2021-09-01 12:45 UTC, davidmfempathy commented on packages/x-components/src/x-modules/search/store/types.ts
> +  setOrigin(origin: QueryOrigin): void;
can we remove it ?

2021-09-01 12:45 UTC, davidmfempathy commented on packages/x-components/src/store/store.types.ts
>  import { Store } from 'vuex';
build failing

2021-09-02 06:09 UTC, javieri-empathy requested changes

2021-09-03 07:47 UTC, davidmfempathy submitted a review, later dismissed

2021-09-03 09:23 UTC, javieri-empathy approved these changes

2021-09-03 09:49 UTC, davidmfempathy approved these changes

2021-09-03 09:50 UTC, merged