Update web-archetype-integration-guide.md
empathyco/x pull request #1349
Opened 2023-11-02 13:03 UTC by mariorey

Added documentation about how to track add2cart event
# Pull request template
 
Describe the purpose of the change, the specific changes done in detail, and the issue you have fixed.

## Motivation and context

- [ ] Dependencies. If any, specify:
- [X] Open issue. If applicable, link: https://searchbroker.atlassian.net/browse/EMP-2699

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [X] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [ ] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2023-11-02 14:29 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md
> +    isSPA: !0,
My example in the task was wrong, I don't know where I copied those values but are not descriptive for developers that have to integrate this:

```suggestion
    scope: 'desktop',
    currency: "EUR",
    consent: true,
    isSPA: false,
```

2023-11-02 14:29 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md
> +#### Tracking the Add2Cart event from PDP
```suggestion
### Tracking the Add2Cart event from PDP
```

This is the correct heading for a new section to be in the same level as the other `Notes on X Archetype integration`

2023-11-02 14:29 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md
> +**NON-SPA**
```suggestion
#### NON-SPA
```

2023-11-02 14:29 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md
> +**SPA**
```suggestion
#### SPA
```

2023-11-02 14:29 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md
> +addToCartButton.addEventListener('click', () =>
```suggestion
yourCommerceStoreEnvironment .addToCartButton.addEventListener('click', () =>
```

In this way they don't think that addToCartButton is a button from Empathy env

2023-11-02 14:29 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md
> +addToCartButton.addEventListener('click', () =>
```suggestion
yourCommerceStoreEnvironment .addToCartButton.addEventListener('click', () =>
```

In this way they don't think that addToCartButton is a button from Empathy env

2023-11-02 14:29 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md
> +if (yourCommerceStoreEnvironment.isPDP && InterfaceX.getSnippetConfig.isSpa) {
```suggestion
if (yourCommerceStoreEnvironment.isPDP && window.initX.isSpa) {
```

I know I told you to place something as getSnippetConfig, but it doesn't exist, so we can use the `initX` object

2023-11-03 08:48 UTC, herrardo commented
Do not merge, waiting for @mlcorton review. :)

2023-11-10 10:58 UTC, mlcorton commented
Hi there @mariorey! I've noticed that code snippets are breaking numbered lists. I've added a new commit to fix it (you need to indent code twice to solve it). Also, I've rewritten some content to make it clearer and match the current style and sentence structure. Tell me if I've misled any concept. :) 
cc: @herrardo

2023-11-10 11:15 UTC, herrardo requested changes

2023-11-10 11:15 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md
> +2. Call the `InterfaceX.addProductToCart('11776347-ES')` function to track the event when the add-to-cart button is clicekd.
```suggestion
2. Call the `InterfaceX.addProductToCart('11776347-ES')` function to track the event when the add-to-cart button is clicked.
```

2023-11-10 11:32 UTC, mlcorton approved these changes

2023-11-13 06:55 UTC, herrardo approved these changes

2023-11-13 08:19 UTC, merged