[EX-4472] Mock adapter for ID results e2e tests
empathyco/x pull request #135
Opened 2021-09-06 10:10 UTC by mavmaf

# Pull Request Template #

- mocked-adapter changed so the ID search can be intercepted by Cypress

- e2e test for the empathize changed to make use of Cypress' intercept

## Motivation and Context ##

We needed to have a reliable method of doing e2e tests without relying on APIs outside of our control. This PR implements a version of that solution for the search.box tests.

## What is the destination branch of this PR? # 

EX-4472

## How Has This Been Tested? ##

Run the tests in Cypress to see the intercept working.
In cypress.json you can change the testFiles property's first element to "cucumber/**/*.features" to be able to select the test to run.

2021-09-06 12:03 UTC, javieri-empathy requested changes

2021-09-06 12:03 UTC, javieri-empathy commented on packages/x-components/tests/e2e/cucumber/identifier-results/identifier-results.feature
> +      | c0 32 |
I think this should be 2 separate scenarios, one is **a matching identifier is searched but it has no results**, and another one is **a non matching identifier is searched**. In this last case the request shouldn't even be made.

2021-09-06 14:04 UTC, mavmaf commented on packages/x-components/tests/e2e/cucumber/identifier-results/identifier-results.spec.ts
> +Given('an ID results API with a known response', () => {
Regarding your first comment, I would leave it as it is now for consistency with the rest of the already mocked tests, which have both an 'generic' interception and another one with some data copied from the real API. **Let's see 2nd reviewer's opinion** and I'll change if needed

As for the second comment, you're absolutely right.

2021-09-08 06:31 UTC, guillei10 approved these changes

2021-09-09 07:38 UTC, javieri-empathy approved these changes

2021-09-09 07:39 UTC, merged