feat(facets): Unify __unknown__ and __unknown-facet__ in a constant
empathyco/x pull request #1351
Opened 2023-11-07 16:00 UTC by annacv

# Pull request template
 
Create `UNKNOWN_FACET_KEY` constant to identify filters without `facetId` (`RawFilter`).

BREAKING CHANGES:
- The `'__unknown-facet__'`  value for a `facetId` is deprecated: it has been replaced by the `UNKNOWN_FACET_KEY` constant, whose value is `'__unknown__'`.

## Motivation and context

Right now we’re identifying unknown facets giving them either` __unknown__` or` __unknown-facet__` as id.
We should unify this and use a constant instead of a plain string.

- [ ] Dependencies. If any, specify:
- [x] Open issue. If applicable, link: [EMP-2674](https://searchbroker.atlassian.net/browse/EMP-2674)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [x] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [x] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [x] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [x] New and existing **unit tests pass locally** with my changes.

[EMP-2674]: https://searchbroker.atlassian.net/browse/EMP-2674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-11-07 16:04 UTC, annacv commented on packages/x-components/src/components/decorators/injection.consts.ts
> +export const FACET_KEY: string | number = '__unknown__';
If I used here `XInjectKey<string | number>`it forced typecasting `FACET_KEY` in several places, and could not manage to make it work properly inside [filter-entity.factory.ts](https://github.com/empathyco/x/pull/1351/files#diff-05dba8b269de2cb9ed3550cc44c32f9b6e50bf8318d97e56d31d13a9f4f3d9c4), so I left it like this.

2023-11-09 12:33 UTC, CachedaCodes requested changes

2023-11-09 12:33 UTC, CachedaCodes commented on packages/x-components/src/components/decorators/injection.consts.ts
> +export const FACET_KEY: string | number = '__unknown__';
```suggestion
export const UNKNOWN_FACET_KEY: string = '__unknown__';
```

2023-11-09 12:33 UTC, CachedaCodes commented on packages/x-components/src/components/decorators/injection.consts.ts
This is the file for the constants that we're injecting in several places of the app, we're not injecting the new constant anywhere so it shouldn't be here.
A better place would be in the facets module. See the history queries module for an example.

2023-11-13 09:09 UTC, CachedaCodes approved these changes

2023-11-16 12:03 UTC, merged