feat(search): handle display tagging from search response
empathyco/x pull request #1388
Opened 2024-01-03 12:05 UTC by CachedaCodes

[EMP-3239](https://searchbroker.atlassian.net/browse/EMP-3239)

## Motivation and context
A new field for the display tagging will be added to the search response to be used on the recommendations. This PR handles that new field for the search response types and the search module.

- [ ] Dependencies. If any, specify:
- [X] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [X] `Main`
- [ ] Other. Specify:

2024-01-04 07:17 UTC, herrardo approved these changes

2024-01-12 08:59 UTC, annacv commented
Cool @CachedaCodes !
Search state is saving the `displayTagging`:
![Captura de pantalla 2024-01-12 a les 9 54 13](https://github.com/empathyco/x/assets/21217131/b4027c15-db4b-450a-aeb3-645e92bb8e74)

I doubt if we should also save this in the tagging state, as well as we do with the `queryTagging` in a `queryTaggingInfo` object. Anyway, if we think it is worth we can deal with it in another task.

2024-01-12 09:03 UTC, annacv requested changes
Just check this test: `src/mappers/responses/__tests__/search-response.mapper.spec.ts`

2024-01-12 09:06 UTC, annacv approved these changes
🎉

2024-01-12 09:06 UTC, merged