feat: allow queries preview with same query but different filters or params
empathyco/x pull request #1392
Opened 2024-01-15 08:13 UTC by lauramargar

# Pull request template
 
In [the current implementation](https://github.com/empathyco/x/pull/1360), we are only saving queries. As a second step, we should also support filters and extraparams, but then we should save the hash of query+filters.

We have used [`js-md5`](https://www.npmjs.com/package/js-md5) hash to make an id to differentiate the same queries but with different filters applied.

There was a problem when dealing with multiple instances of the `QueryPreview` component with the same query hash. In that case, the order of mounting and unmounting the components matter and it could lead to a scenario where a component is mounted but afterwards, the other one with the same query hash is unmounted and both of them will be gone from the DOM.

We have applied the following **SOLUTION**:

Refactor the events emitted from `QueryPreview`. Remove `NonCacheableQueryPreviewUnmounted` and add `QueryPreviewMounted: string;` `QueryPreviewUnmounted: { query: string, cache: boolean };`

Enhance the `QueryPreviewItem` from the state with a field 
```
  /** The number of instances showing the query preview*/
  instances: number;
```

The `fetchAndSaveQueryPreview` action will set the instances field to 1 since it will be the first instance of a `QueryPreview` using this query hash.

Every `QueryPreview` instance when is created and picks the data from the cache will emit `QueryPreviewMounted` so the instances count is increased. Every instance of `QueryPreview` will emit `QueryPreviewUnmounted` so the instances count for that query hash will be decreased and if the cache is set to false, then the query will be removed safely from the state since there will be no component showing that data.

## Motivation and context

- [ ] Dependencies. If any, specify:
- [X] Open issue. If applicable, link: [EMP-3079](https://searchbroker.atlassian.net/browse/EMP-3079)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [X] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [X] `Main`
- [ ] Other. Specify:

## How has this been tested?

You can test 2 scenarios:

1. Same query + different filters
2. Same query in different instances

In **scenario 1** --> you can add in `Home.vue` file this new query preview in `queriesPreviewInfo` : 
```
{
  query: 'summer dress',
  filters: ['brand:marni']
}
```
You should see 2 carrousels with 'summer dress' as the title but with different results.

In **scenario 2** --> add in the same place as the previous scenario the following query preview:
```
{
  query: 'charger'
}
```
Then search for `battery` in the search box. This query has the query `charger` as a semantic query. 
As we had saved `charger` in the state from the brand recommendations, in semantic queries should be loaded from the state instead of being requested again.

Once we clear the query in the search box, we should see that `charger` keeps saved in the query preview state and is displayed as a brand recommendation.

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [ ] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2024-01-15 13:33 UTC, annacv submitted a review, later dismissed
Also tested with:`{ query: 'wallet', filters: ['brand:valentino']},` as a queryPreview + searching for `charger` to check that Semantic Queries will show results for the query `wallet` without being filtered.

2024-01-16 15:37 UTC, diegopf requested changes

2024-01-16 15:37 UTC, diegopf commented on packages/x-components/src/x-modules/queries-preview/components/query-preview.vue
> +    public queryOfQueryPreview = getHashFromQueryPreviewInfo(this.queryPreviewInfo);
I would rename it from `queryOfQueryPreview` to something like `queryOfQueryPreviewHash` or similar so it is clear that we are dealing with a hash.

2024-01-16 15:37 UTC, diegopf commented on packages/x-components/src/x-modules/queries-preview/components/query-preview.vue
> +      const previewItemQuery = this.queryOfQueryPreview;
I think we can skip the `previewItemQuery` variable and just use `this.queryOfQueryPreview`

2024-01-16 15:37 UTC, diegopf commented on packages/x-components/src/x-modules/queries-preview/components/query-preview.vue
> +        this.$x.emit('QueryPreviewMounted', this.queryOfQueryPreview, {
Following the above comment, here we are using `previewItemQuery` and in the next line `this.queryOfQueryPreview` but both are the same. We should just use `this.queryOfQueryPreview` everywhere.

2024-01-16 15:37 UTC, diegopf commented on packages/x-components/src/x-modules/queries-preview/events.types.ts
> +  QueryPreviewRequestUpdatedForNoCache: SearchRequest;
do we need this event?

2024-01-16 15:37 UTC, diegopf commented on packages/x-components/src/x-modules/queries-preview/utils/get-hash-from-query-preview.ts
where are the tests for these utils? 🙃 We should add some unit tests

2024-01-24 12:47 UTC, CachedaCodes requested changes

2024-01-24 12:47 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/utils/get-hash-from-query-preview.ts
> +  }
You can refactor to this:

```suggestion
  const queryPreviewFilters = queryPreviewInfo.filters ? queryPreviewInfo.filters.join('-') : '';
```

2024-01-24 12:47 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/utils/get-hash-from-query-preview.ts
> +  }
You can refactor this to:

```suggestion
  const queryPreviewFilters = Object.values(queryPreview.request.filters)
  .flat()
  .map(filter => filter.id.toString())
  .join('-');
```

2024-01-24 12:47 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/utils/__tests__/utils.spec.ts
Make the QP in the tests have filters. Half of the implementation is not being tested right now

2024-01-24 12:47 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/components/query-preview-list.vue
> +        const query = getHashFromQueryPreviewInfo(item);
Rename to `queryPreviewHash`

2024-01-24 12:47 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/components/__tests__/query-preview-list.spec.ts
> +  // TODO Uncomment when the 'error' event is fixed
If there's a task already, add the task ID here

2024-01-25 07:23 UTC, CachedaCodes requested changes
Fix the conflicts with main too

2024-01-25 07:23 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/store/module.ts
> +    addQueryPreviewInstance(state, queryPreviewHash: string) {
No need to specify the type in `queryPreviewHash: string`, it's already being done in the types file, remove the `string`.

2024-01-25 07:23 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/store/module.ts
> +      { queryPreviewHash, cache }: { queryPreviewHash: string; cache: boolean }
Same here, you don't need the type in ` { queryPreviewHash, cache }: { queryPreviewHash: string; cache: boolean }`, leave it as ` { queryPreviewHash, cache }`

2024-01-25 07:23 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/store/types.ts
> +  addQueryPreviewInstance(queryPreviewHash: string): void;
Add docs

2024-01-25 07:23 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/store/types.ts
> +  removeQueryPreviewInstance({
Add docs

2024-01-25 07:23 UTC, CachedaCodes commented on packages/x-components/src/x-modules/queries-preview/components/__tests__/query-preview-list.spec.ts
> +  // TODO Uncomment when the 'error' event is fixed
Reference task EMP-3402

2024-01-25 08:42 UTC, CachedaCodes approved these changes

2024-01-25 08:54 UTC, merged