Update facets' module when we change preselected filters in the snippetConfig
empathyco/x pull request #1404
Opened 2024-02-07 09:05 UTC by annacv

[EMP-3398](https://searchbroker.atlassian.net/browse/EMP-3398)

When we have preselected filters and want to change or update them using the `setSnippetConfig` function, there is a bug: the `PreselectedFilters` component is updated, but the facets' module is not.

To solve this I've defined a computed property to set the preselected filters and a watcher to emit the `PreselectedFiltersProvided` event when it changes.

While this component is meant [to select the preselected filters when `UserClickedOpenX` is fired](https://github.com/empathyco/x/blob/main/packages/x-components/src/x-modules/facets/wiring.ts#L232), by watching the computed property now we can see the state updated instantly. However, this change won't be instant in setups that have filters defined as sticky (which is [dutty](https://github.com/empathyco/x-massimodutti-next/blob/main/src/main.ts) use case).

**TEST** 
**Test in x-components:**
1. Open X and paste this code in the console: 
```
InterfaceX.setSnippetConfig({
  filters: [`brand:adidas`],
});
```
2. Search for `trousers` or `dress`: the preselected filter should be shown as selected & the rendered results should work as expected.
3. Delete the query & change the preselected filters:
```
 InterfaceX.setSnippetConfig({
  filters: [`brand:marni`],
});
```
4. Search for `trousers` or `dress`: the preselected filter has changed & the rendered results should work as expected.

**Test in dutty:**
1. Run a build process in `x-components` & install the version locally in dutty
2. Remove [the watcher](https://github.com/empathyco/x-massimodutti-next/blob/main/src/App.vue#L75) in dutty `App.vue` file
3. Follow the steps defined in [this PR](https://github.com/empathyco/x-massimodutti-next/pull/80)

2024-02-09 10:32 UTC, lauramargar commented
Great job!! For me it's ok!! 
Only one thing to comment, add the injectionKey `@Inject('snippetConfig')`

2024-02-09 10:53 UTC, annacv commented
Hi! Please @lauramargar help me test again on Monday, it seems that is not saving the preselected filters on a second search. Steps: 
1. Set preselected via console
2. Open X & search ('dress')
3. Clear query & search again (I removed dress from histories & then searched again)
4. Filter is not kept in the second search

2024-02-12 09:43 UTC, lauramargar approved these changes

2024-02-13 10:27 UTC, CachedaCodes requested changes

2024-02-13 10:27 UTC, CachedaCodes commented on packages/x-components/src/x-modules/facets/components/preselected-filters.vue
> +    protected emitPreselectedFilters(): void {
You can put the watcher here and still call the function independently

```suggestion
    @Watch('preselectedFilters')
    protected emitPreselectedFilters(): void {
```

2024-02-13 10:27 UTC, CachedaCodes commented on packages/x-components/src/x-modules/facets/components/preselected-filters.vue
> +    }
You don't need this

2024-02-13 10:27 UTC, CachedaCodes commented on packages/x-components/src/x-modules/facets/components/preselected-filters.vue
Add a test that checks that the event is emitted when the snippet config changes.

2024-02-21 08:35 UTC, CachedaCodes approved these changes

2024-02-21 08:37 UTC, merged