feat(tagging): send query event when a result from a QP is clicked
empathyco/x pull request #1409
Opened 2024-02-15 12:27 UTC by lauramargar

# Pull request template
 
Carrousel previews are tagged with a new event “displayclicked” but this info doesn’t impact the CTR or Findability metric therefore queries are growing but CTR and Findability are suffering.
When a user clicks on a product in the carousel the query event with the origin has to be sent and the click and displayClick events.

## Motivation and context

- [ ] Dependencies. If any, specify:
- [X] Open issue. If applicable, link: [EMP-3521](https://searchbroker.atlassian.net/browse/EMP-3521)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [X] `Main`
- [ ] Other. Specify:

## How has this been tested?

Click on a result of a query preview. The first time you click on a result in one carousel 3 events should be sent (click, displayClick and query). Suppose you click on another result of the same carousel, only 2 events will be sent (click and displayClick). In that case, the tagging module has stored the queryTaggingInfo of the carousel. If you try to click in another carousel, the 3 events will be sent again.

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [ ] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2024-02-16 10:32 UTC, CachedaCodes requested changes

2024-02-16 10:32 UTC, CachedaCodes commented on packages/x-components/src/x-modules/tagging/wiring.ts
> +    setQueryTaggingFromQueryPreview
Aren't these two events basically the same? We can use just `UserClickedADisplayResult` with the `resultLinkMetadataPerEvent` in its metadata and make it also call `setQueryTaggingFromQueryPreview` when it's listened:

```suggestion
  UserClickedADisplayResult: {
    trackDisplayClickedWire,
    setQueryTaggingFromQueryPreview
```

2024-02-19 09:19 UTC, CachedaCodes approved these changes

2024-02-19 09:19 UTC, merged

2024-03-07 16:29 UTC, herrardo commented
When a carousel item is clicked, the `displayclick` event should be fired. And then should crossed agains the `display `event, that is sent when a carousel is loaded. to calculate a display CTR.

Firing `query `and `click `events when a carousel is clicked seems a bad approach, but i guess Germán won :)

2024-03-08 08:13 UTC, diegopf commented
@herrardo vuelve