Feature/emp 3542 migrate global x bus component
empathyco/x pull request #1429
Opened 2024-03-11 07:41 UTC by albertjcuac

# Pull request template
 
For the vue 3 migration we need to migrate components to 2.7

## Motivation and context

- [ ] Dependencies. If any, specify:
- [X] Open issue. If applicable, link: [EMP-3542](https://searchbroker.atlassian.net/browse/EMP-3542)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [X] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

testing it still works following the docs usage: [link](https://docs.empathy.co/develop-empathy-platform/ui-reference/components/base-components/x-components.global-x-bus.html)

2024-03-11 09:22 UTC, albertjcuac commented
Snippet callbacks tests have been commented because they have not been migrated yet and they use globalXbus , so we need to avoid them failling for this PR and fix them in the Snippet Callbacks migration task.

2024-03-12 09:35 UTC, CachedaCodes requested changes

2024-03-12 09:35 UTC, CachedaCodes commented on packages/x-components/src/components/__tests__/snippet-callbacks.spec.ts
>  describe('testing SnippetCallbacks component', () => {
Revert the changes here and skip these tests, they'll be fixed in the snippet callbacks task

```suggestion
describe.skip('testing SnippetCallbacks component', () => {
```

2024-03-12 09:35 UTC, CachedaCodes commented on packages/x-components/src/components/__tests__/global-x-bus.spec.ts
>    const [, localVue] = installNewXPlugin();
The x plugin is getting deprecated, so don't use `installNewXPlugin` (not even sure if you need it for this test)

2024-03-12 09:35 UTC, CachedaCodes commented on .eslintrc.js
> +    'packages/x-components/src/components/__tests__/snippet-callbacks.spec.ts'
```suggestion
```

2024-03-12 09:35 UTC, CachedaCodes commented on packages/x-components/src/components/__tests__/global-x-bus.spec.ts
Add a test checking that the subscriptions are unsubscribed when the GlobalXBus component is unmounted.

2024-03-12 14:26 UTC, annacv approved these changes
🎉

2024-03-13 08:15 UTC, merged