Add new URLManager component
empathyco/x pull request #146
Opened 2021-09-13 12:02 UTC by pmareke

EX-4566

2021-09-13 14:10 UTC, tiborux requested changes

2021-09-14 05:09 UTC, pmareke commented on packages/x-components/src/x-modules/url/components/url-manager.vue
> +      if (Object.keys(this.$attrs).length > 0) {
Taking a look inside the project, we're using always the comparison against zero:

![image](https://user-images.githubusercontent.com/3502075/133198365-5b61864e-783f-4749-b351-3780a3cbe7a3.png)

So I prefer to be consistent and keep using the same, what do you think?

2021-09-14 05:09 UTC, pmareke commented on packages/x-components/src/x-modules/url/components/url-manager.vue
> +        const params = Object.entries(this.$attrs).reduce((acc, [key, value]) => {
Why do we have a `reduce` method, which does the same as the one from Javascript?

2021-09-14 05:18 UTC, pmareke commented on packages/x-components/src/x-modules/url/components/__tests__/url-manager.spec.ts
> +  it('is an x-component', () => {
I follow the same approach as the `DeviceDetector` component:

![image](https://user-images.githubusercontent.com/3502075/133199117-70dce6dd-ae33-4872-8c95-c7397f926565.png)

2021-09-14 05:18 UTC, pmareke commented on packages/x-components/src/x-modules/url/components/url-manager.vue
> +<script lang="ts">
I like URLHandler!

2021-09-14 05:38 UTC, pmareke commented on packages/x-components/src/x-modules/url/components/__tests__/url-manager.spec.ts
> +}
Honestly I'm not sure.

I didn't do it because it was more a browser API thing that ours, but I can give it a try sure.

2021-09-14 06:36 UTC, tiborux commented on packages/x-components/src/x-modules/url/components/url-manager.vue
> +      if (Object.keys(this.$attrs).length > 0) {
lets do it then 👌

2021-09-15 11:26 UTC, guillei10 commented on packages/x-components/src/x-modules/url/components/url-handler.vue
> +It also emit the `DocumentLoaded` when the page is loaded and the `DocumentHistoryChanged` when the
* emits

2021-09-15 11:26 UTC, guillei10 commented on packages/x-components/src/x-modules/url/components/url-handler.vue
> +_Try to make some request and take a look to the url!_
* some requestS

2021-09-15 11:26 UTC, guillei10 commented on packages/x-components/src/x-modules/url/components/url-handler.vue
> +This component doesn't render elements to the DOM, but serves as way to easily change the default
*serves as a way

2021-09-16 06:42 UTC, tiborux requested changes

2021-09-16 06:59 UTC, tiborux approved these changes

2021-09-16 09:57 UTC, guillei10 approved these changes

2021-09-16 09:57 UTC, merged