feat: add the capability to reload the current search
empathyco/x pull request #1515
Opened 2024-06-11 14:37 UTC by manuel-cid

# Pull request template
We need a way to *refresh* the results displayed on the search layer.

## Motivation and context

This requirement comes from the Backroom's next functionality, boost&bury of single products by query. After boosting or burying a product, we need a way to re-do the current search and refresh the results to see the change applied.
The idea is to emit the event `ReloadSearchRequested` through the x-bus and trigger a mutation on the state that triggers the search request.

- [ ] Dependencies. If any, specify:
- [ ] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [x] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [ ] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2024-06-12 07:13 UTC, alvarodE approved these changes

2024-06-13 12:18 UTC, alvarodE approved these changes

2024-06-17 08:33 UTC, manuel-cid commented on packages/x-components/src/x-modules/search/store/module.ts
> +      Object.assign(state, resettable);
Done

2024-06-17 08:53 UTC, diegopf requested changes

2024-06-17 08:53 UTC, diegopf commented on packages/x-components/src/x-modules/search/events.types.ts
> +  ReloadSearchRequested: undefined;
```suggestion
  ReloadSearchRequested: void;
```

2024-06-17 08:55 UTC, diegopf approved these changes

2024-06-17 09:11 UTC, merged