Feature/ex 4712 as a developer i want to update the store from the URL
empathyco/x pull request #152
Opened 2021-09-15 08:12 UTC by guillei10

#Description #

The goal of this PR is to implement the action that will allow the Url module to receive parameters from the url and update the state. 

In order to do this, the action has to check one by one all the params from the state and look if some of them have been updated or added in the url. Then it also validates which type is the parameter in the state to be able to parse the url value from the url to the state with the correct type.

## Motivation and Context ##

This is part of the url module implementation. There are also some changes to adapt from previous PRs about this module.

## Test  ##

As previous PRs, you can add a wire that links an Event with this action and fire that event in the interface. Then you can debug the state of the module to see if it updates accordingly.

2021-09-15 09:03 UTC, pmareke requested changes

2021-09-15 09:03 UTC, pmareke commented on packages/x-components/src/x-modules/url/store/actions/update-store-from-url.action.ts
> +    case 'boolean':
At this point you're sure that the value is present, so you can use:

```javascript
case 'boolean':
  return urlSearchParams.get(urlParam)!.toLowerCase() === 'true';
case 'string':
  return urlSearchParams.get(urlParam)!;
```

2021-09-15 10:32 UTC, tiborux requested changes

2021-09-15 10:32 UTC, tiborux commented on packages/x-components/src/x-modules/url/store/types.ts
>  /**
Can you document the mutations? The documentation is missing.

2021-09-15 10:32 UTC, tiborux commented on packages/x-components/src/x-modules/url/store/actions/update-store-from-url.action.ts
> + * @param urlSearchParams - All the search params
All these sentences needs a dot at the end.

2021-09-16 05:59 UTC, pmareke requested changes
The build is failing because of the type of the `setParams` mutation:

https://github.com/empathyco/x/pull/152/checks?check_run_id=3609406247#step:4:235

It should be a `Dictionary<Params>`

2021-09-16 09:56 UTC, pmareke approved these changes

2021-09-16 09:58 UTC, pmareke approved these changes
Great job!

2021-09-16 11:26 UTC, pmareke approved these changes

2021-09-16 11:30 UTC, tiborux approved these changes

2021-09-16 11:45 UTC, merged