Update url action regarding pusheable parameters
empathyco/x pull request #158
Opened 2021-09-16 09:56 UTC by pmareke

EX-4713

2021-09-16 12:25 UTC, tiborux requested changes

2021-09-16 12:25 UTC, tiborux commented on packages/x-components/src/x-modules/url/store/__tests__/actions.spec.ts
> +  describe(`${actionKeys.updateStoreFromUrl}`, () => {
Remove this describe, its duplicated.

2021-09-16 12:25 UTC, tiborux commented on packages/x-components/src/x-modules/url/store/__tests__/actions.spec.ts
> +      expect(window.history.pushState).toHaveBeenCalled();
As you said, maybe we can add another test to check replaceSate or we can add it in the first It:

```
    it('should add the correct params to the url', async () => {
       window.history.replaceState = jest.fn();
       .
      .
      expect(window.history.replaceState).toHaveBeenCalled();
```

2021-09-17 08:12 UTC, guillei10 requested changes

2021-09-20 06:23 UTC, guillei10 approved these changes

2021-09-20 06:41 UTC, tiborux approved these changes

2021-09-20 06:43 UTC, merged