fix(design-system): facet alignment in firefox
empathyco/x pull request #1587
Opened 2024-08-06 12:20 UTC by lauramargar

# Pull request template
 
Facets' icons are misaligned in Firefox.

![Screenshot 2024-08-06 at 11 20 55](https://github.com/user-attachments/assets/ef1f9eba-c5b6-4bff-8c20-b1da36845730)

## Motivation and context

- [ ] Dependencies. If any, specify:
- [X] Open issue. If applicable, link: [EMP-4657](https://searchbroker.atlassian.net/browse/EMP-4657)

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [X] `Main`
- [ ] Other. Specify:

## How has this been tested?

Check the filters in the facets panel in the Firefox browser.

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [ ] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2024-08-06 13:59 UTC, diegopf requested changes
Now it seems both chrome and firefox are not aligned 😅  we need a better option

2024-08-08 07:43 UTC, lauramargar commented
> Now it seems both chrome and firefox are not aligned 😅 we need a better option

If we change grid display to flex, it seems to work. 

![Screenshot 2024-08-08 at 09 43 02](https://github.com/user-attachments/assets/39d4fc67-b929-4c21-b76b-8198e3e548f2)

![Screenshot 2024-08-08 at 09 42 58](https://github.com/user-attachments/assets/2672f044-8fc1-404c-97cc-ab061d26a1ba)

2024-08-08 08:37 UTC, annacv approved these changes

2024-08-13 14:56 UTC, diegopf approved these changes

2024-08-13 14:56 UTC, merged