[EX-4759] Update Cypress version
empathyco/x pull request #162
Opened 2021-09-17 10:15 UTC by mavmaf

# Pull request template
In order to update Cypress version, `npm install --save-dev cypress@8.4.0` was run and it was also needed to manually change the version in `packages/react-wrapper/package.json` and `packages/x-components/package.json`.

## Motivation and context
Several improvements have been made since v7.7.0. Some of them are the following:

- Projects will now open much faster on MacOS Big Sur with improved browser detection performance
- Fixed a regression in 7.2.0 that would cause cy.visit() to take longer to fire its load event in some circumstances
- Fixed a regression in 8.3.0 where the correct exit code would not be issued during cypress run-ct 
- Upgraded Chrome browser version used during cypress run 
- Multiple fixes for cy.intercept

## What is the destination branch of this PR?
- `Main`

## How has this been tested?

Run tests using Cypress

2021-09-20 06:06 UTC, pmareke approved these changes
Great job, everything works fine as before so for me it's ok!

2021-09-20 06:35 UTC, pmareke requested changes
In order to use the latest version of Cypress (8.4.1), please run `npm update`, discard the changes in the package.json and just leave the ones in the package-lock.json.

2021-09-20 13:49 UTC, pmareke requested changes
Leave the changes only in the lock files.

2021-09-20 13:49 UTC, pmareke commented on package.json
> +    "conventional-changelog-conventionalcommits": "^4.6.1",
Revert the changes of this file please, we only need the ones in the lock files.!

2021-09-20 13:49 UTC, pmareke commented on packages/react-wrapper/package.json
> +    "cypress": "~8.4.1",
Revert the changes of this file please, we only need the ones in the lock files.!

2021-09-20 13:49 UTC, pmareke commented on packages/x-components/package.json
> +    "cypress": "~8.4.1",
Revert the changes of this file please, we only need the ones in the lock files.!

2021-09-21 08:31 UTC, CachedaCodes submitted a review, later dismissed

2021-09-21 09:59 UTC, pmareke approved these changes
Top!

2021-09-21 10:00 UTC, CachedaCodes approved these changes

2021-09-21 10:02 UTC, merged