feat(url): syncronize url and state with the query
empathyco/x pull request #165
Opened 2021-09-20 10:06 UTC by tiborux

Run the project, and check how the url is updated with the query and in the other way around, if you type a query on the url, xcomponents will be opened and it will be set the new query.

EX-3509

2021-09-20 13:07 UTC, pmareke requested changes
Well done!

2021-09-20 13:07 UTC, pmareke commented on packages/x-components/src/utils/string.ts
> + * @param str - String value.
Add a blank line below please.

2021-09-20 13:07 UTC, pmareke commented on packages/x-components/src/utils/string.ts
> + * @returns Returns the string capitalized.
Add a blank line below please.

2021-09-20 13:07 UTC, pmareke commented on packages/x-components/src/x-modules/url/components/__tests__/utils.ts
> +import { Store } from 'vuex';
Remove this file please.

2021-09-20 13:07 UTC, pmareke commented on packages/x-components/src/x-modules/url/components/__tests__/url-handler.spec.ts
>    return {
Add a new line above and remove constants:

```javascript
  return {
    wrapper: wrapperTemplate.findComponent(UrlHandler),
    $x: wrapperTemplate.vm.$x
  };
```

2021-09-20 13:18 UTC, pmareke approved these changes

2021-09-21 09:23 UTC, pmareke approved these changes

2021-09-21 09:40 UTC, guillei10 approved these changes

2021-09-21 09:40 UTC, merged