Cleanup and format code
empathyco/x pull request #170
Opened 2021-09-21 09:56 UTC by javieri-empathy

# Description

Adds a new design component, the `badge`. This can be used to display minimal amounts of information on top of other components. For example with the selected filters count.

![image](https://user-images.githubusercontent.com/68222542/134151053-9bb96c26-61d6-4906-8473-db7db77a43fe.png)

2021-09-21 11:09 UTC, pmareke requested changes
Grande capo!

2021-09-21 11:09 UTC, pmareke commented on packages/x-components/src/design-system/components/badge/default.scss
> +  border-radius: 50%;
This border radius is going to be always round? Should be allow the option to change it?

2021-09-21 11:09 UTC, pmareke commented on packages/x-components/src/design-system/components/badge/default.scss
> +  text-align: center;
Move to the layout section please.

```css
// layout
position: absolute;
text-align: center;
vertical-align: middle;
```

2021-09-22 06:18 UTC, tajespasarela approved these changes

2021-09-22 06:37 UTC, merged