chore(x-plugin): refactor and clean the code
empathyco/x pull request #180
Opened 2021-10-01 09:55 UTC by tajespasarela

# Pull request template
 
Describe the purpose of the change, the specific changes done in detail, and the issue you have fixed.

## Motivation and context

- [ ] Dependencies. If any, specify:
- [ ] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [ ] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [ ] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2021-10-01 10:17 UTC, pmareke requested changes
Fix the build please.

2021-10-01 10:17 UTC, pmareke commented on packages/x-components/src/plugins/x-emitters.ts
> +import { debounce } from '../utils/debounce';
Remove unused import.

2021-10-01 10:17 UTC, pmareke commented on packages/x-components/src/plugins/x-emitters.ts
> + * @internal
Remove duplicate internal

2021-10-01 10:17 UTC, pmareke commented on packages/x-components/src/plugins/x-plugin.ts
> +   * @returns The customized xModule.
Add missing `@public`

2021-10-05 10:20 UTC, CachedaCodes requested changes

2021-10-06 09:52 UTC, pmareke requested changes
Some minor things.

2021-10-06 09:52 UTC, pmareke commented on packages/x-components/src/plugins/x-emitters.ts
> + * @internal
I would add a blank line above as in the `registerStoreEmitters `.

2021-10-06 09:52 UTC, pmareke commented on packages/x-components/src/plugins/x-emitters.ts
> + * @internal
Same here.

2021-10-06 09:52 UTC, pmareke commented on packages/x-components/src/plugins/x-plugin.ts
> +   * @public
Same here.

2021-10-06 11:08 UTC, pmareke approved these changes

2021-10-06 11:21 UTC, CachedaCodes approved these changes

2021-10-06 11:21 UTC, merged