Add storage service package
empathyco/x pull request #19
Opened 2021-06-17 09:17 UTC by pmareke

EX-3844

Add the `storage service` package to the mono repository

2021-06-17 12:24 UTC, LuisMartinez15 requested changes

2021-06-17 12:24 UTC, LuisMartinez15 commented on packages/storage-service/Jenkinsfile
> +}
This file is no longer needed, right?

2021-06-17 12:24 UTC, LuisMartinez15 commented on packages/storage-service/tslint.json
> +}
Remove unnecessary file

2021-06-18 08:58 UTC, LuisMartinez15 approved these changes

2021-06-23 10:14 UTC, CachedaCodes approved these changes

2021-06-23 10:21 UTC, merged