feat(url): set sort values and read them from the url.
empathyco/x pull request #201
Opened 2021-10-28 09:18 UTC by guillei10

# Description

The goal of this PR is to add the sort to the url flow. Now we will be able to load the sort from the url and also the url is being updated with the values of the sort. Things done:

- Removed the `value` prop from the `Sort` _mixin_. When used it caused duplicated requests.
- Added mutation and wiring in the url module to be updated when the sort changes.
- Changed the action in search module that allows to update the search state with the values coming from the url

2021-11-01 08:02 UTC, CachedaCodes requested changes

2021-11-01 08:02 UTC, CachedaCodes commented on packages/x-components/src/x-modules/search/components/__tests__/sort-dropdown.spec.ts
>    items = ['Relevance', 'Price low to high', 'Price high to low'],
Given that we agreed to have the default value be `''`, should we replace `'Relevance'` here with `''`?

2021-11-01 08:02 UTC, CachedaCodes commented on packages/x-components/src/x-modules/search/components/__tests__/sort-list.spec.ts
>    items = ['Relevance', 'Price low to high', 'Price high to low'],
Same as before, should we replace `''Relevance` with `''`?

2021-11-02 18:07 UTC, guillei10 commented on packages/x-components/src/x-modules/search/components/__tests__/sort-dropdown.spec.ts
> +      items: ['price desc', 'price asc', '']
I just changed the items to make it consistent and make one of the items to be `''` as it is the default value. I'm changing the description.

2021-11-02 18:10 UTC, guillei10 commented on packages/x-components/src/x-modules/search/components/sort.mixin.ts
> +    return this.selectedSort ?? this.items[0];
I think so.

2021-11-03 11:21 UTC, tiborux commented
Should we document that the default value will be always ''? I mean, if you are sending items=['1','2','3'] the component will render also ' ' because its the default value so I dont know if we have to document that the user have to add '' as the first item or warn him that he will see '' as default value.

2021-11-03 12:40 UTC, CachedaCodes requested changes

2021-11-03 12:40 UTC, CachedaCodes commented on packages/x-components/src/x-modules/search/components/__tests__/sort-dropdown.spec.ts
> +      items: ['price desc', 'price asc', '']
As we just discussed, it's weird having `''` as the default value, even knowing that the adapter will treat this value as sorting by relevance we would have kind of hardcode it in the front to represent that in the sort dropdown or whatever we're using for sorting. 

Setting `items[0]` as the default value for the `selectedSort` or a good way of representing the default value to the customer would be better.

2021-11-03 13:57 UTC, CachedaCodes submitted a review, later dismissed

2021-11-03 14:22 UTC, tiborux requested changes

2021-11-03 15:45 UTC, CachedaCodes approved these changes

2021-11-03 15:48 UTC, tiborux approved these changes

2021-11-03 15:48 UTC, merged