Feature/remove x installer from router hooks
empathyco/x pull request #216
Opened 2021-11-07 21:20 UTC by JaviIG

# Pull request template

`XInstaller` was being used weirdly in the test views. `XInstaller`is a utility to create a Vue application, not modifying it after the instantion.

## Motivation and context

This simplifies test views code and ensures same API across all of them.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [ ] `Main`
- [ ] Other. Specify:

## How has this been tested?

E2e tests keep working

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [ ] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2021-11-08 09:05 UTC, pmareke submitted a review, later dismissed

2021-11-10 10:45 UTC, LuisMartinez15 requested changes
Can you also remove the `beforeRouteEnter` hook in the `FullNoEmpathize` view? The rest looks fine to me. Thank you and good job! 💪🏿

2021-11-11 07:19 UTC, LuisMartinez15 submitted a review, later dismissed
LVIPGTM

2021-11-11 07:42 UTC, pmareke submitted a review, later dismissed

2021-11-12 08:30 UTC, LuisMartinez15 approved these changes

2021-11-12 09:35 UTC, pmareke approved these changes

2021-11-12 09:36 UTC, merged