Feature/ex 5189 reset scroll on more events
empathyco/x pull request #282
Opened 2021-12-23 12:16 UTC by javieri-empathy

EX-5189

- Exposes a prop to change the events that should reset the scroll position. For example, when searching, changing filters, related tags. 
- Changing an extra param has also been added as a trigger for resetting the scroll position
- Adds e2e tests for this feature.

2021-12-23 13:18 UTC, LuisMartinez15 commented on packages/x-components/src/components/scroll/base-scroll.vue
> +You can configure which events make the scroll position be reset using the `resetOn` prop.
```suggestion
You can configure which events reset the scroll position using the `resetOn` prop.
```

2021-12-23 13:39 UTC, LuisMartinez15 submitted a review, later dismissed

2021-12-24 08:25 UTC, pmareke requested changes

2021-12-24 08:25 UTC, pmareke commented on packages/x-components/src/components/scroll/scroll.mixin.ts
> +import { XEvent } from '../../wiring/index';
```suggestion
import { XEvent } from '../../wiring/events.types';
```

2021-12-24 09:27 UTC, LuisMartinez15 approved these changes

2021-12-24 09:35 UTC, pmareke approved these changes

2021-12-24 09:44 UTC, merged