feat(next-queries): update next queries to use the isCurated property
empathyco/x pull request #287
Opened 2021-12-28 15:31 UTC by CachedaCodes

Next Queries now have the property `isCurated`. This PR adds support for the use of that property.

The `NextQuery` component now adds a CSS class to highlight when the NQ is curated. It's also dependant on a new prop set to `false` by default.
The `NextQueries` component also has the same new prop as `NextQuery` that would affect every NQ inside the component.
New tests for the new functionality were also added.

* General efactor of the Next Queries and Next Query.
* Small change in a Related Tag test (out of scope but stumbled upon it)

[EX-5199](https://searchbroker.atlassian.net/browse/EX-5199)

2021-12-29 06:28 UTC, pmareke requested changes
Nice, well done!

2021-12-29 06:28 UTC, pmareke commented on packages/x-components/src/x-modules/next-queries/components/next-query.vue
> +            @binding {boolean} highlightCurated - True if the curated NQ should be highlighted
```suggestion
@binding {boolean} shouldHighlightCurated - True if the curated NQ should be highlighted
```

2021-12-29 06:28 UTC, pmareke commented on packages/x-components/src/x-modules/next-queries/components/__tests__/next-queries.spec.ts
> +        return findTestDataById('next-query-item');
```suggestion
return wrapper.findAll(getDataTestSelector('next-query-item'));
```

2021-12-29 06:28 UTC, pmareke commented on packages/x-components/src/x-modules/next-queries/components/__tests__/next-queries.spec.ts
> +    const findTestDataById = (testDataId: string): WrapperArray<Vue> =>
```suggestion

```

2021-12-29 06:28 UTC, pmareke commented on packages/x-components/src/x-modules/next-queries/components/__tests__/next-queries.spec.ts
> +      wrapper.findAll(getDataTestSelector(testDataId));
```suggestion
```

2021-12-29 06:28 UTC, pmareke commented on packages/x-components/src/x-modules/next-queries/components/__tests__/next-queries.spec.ts
>            <template #suggestion="suggestionScope">
```suggestion
 <template #suggestion="{ suggestion, highlightCurated, index }">
```

Also remove the `suggestionScope.` bellow.

2021-12-29 06:28 UTC, pmareke commented on packages/x-components/src/x-modules/next-queries/components/__tests__/next-query.spec.ts
> +import { XComponentAPI } from '../../../../plugins/index';
```suggestion
import { XComponentAPI } from '../../../../plugins/x-plugin.types';
```

2021-12-29 06:28 UTC, pmareke commented on packages/x-components/src/x-modules/next-queries/components/__tests__/next-queries.spec.ts
> +import { XPlugin } from '../../../../plugins/index';
```suggestion
import { XPlugin } from '../../../../plugins/x-plugin';
```

2021-12-30 12:15 UTC, diegopf requested changes

2021-12-30 15:04 UTC, diegopf approved these changes

2021-12-31 09:11 UTC, pmareke approved these changes

2021-12-31 09:11 UTC, merged