docs: sanity checks
empathyco/x pull request #293
Opened 2022-01-05 09:02 UTC by herrardo

Sanity Checks

# Pull request template
Fix bugs that Luisa found on this document https://searchbroker.atlassian.net/wiki/spaces/ED/pages/3639738373/Sanity+check+notes

## Motivation and context
Correct links and update callout viz.

- [ ] Dependencies. If any, specify:
- [X] Open issue. If applicable, link: EX-5035

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [X] Change requires a documentation update

## What is the destination branch of this PR?

- [X] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [X] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2022-01-07 12:19 UTC, javieri-empathy requested changes

2022-01-07 12:19 UTC, javieri-empathy commented on packages/x-components/static-docs/build-search-ui/web-x-components-integration-guide.md
>  **[Interface X Archetype Development](/develop-empathy-platform/build-search-ui/web-archetypedevelopment-guide.md)**.
Should this link also be changed to 
```suggestion
**[Interface X Archetype Development](web-archetype-development-guide.md)**.
```

2022-01-07 15:00 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/README.md
> +- **[Use & configure the Interface X Components](#use-configure-the-interface-x-components)** in
Suggestion applied

2022-01-07 15:01 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-x-components-integration-guide.md
>  **[Interface X Archetype Development](/develop-empathy-platform/build-search-ui/web-archetypedevelopment-guide.md)**.
Suggestion applied

2022-01-10 11:13 UTC, javieri-empathy commented on packages/x-components/static-docs/build-search-ui/README.md
> +- **[Use & configure the Interface X Components](#use-configure-the-interface-x-components)** in
I meant that this link won't work both in GitHub and EmpathyDocs at the same time. GitHub renders the id of the header with an extra `-` that [EmpathyDocs](https://docs.empathy.co/develop-empathy-platform/build-search-ui/?utm_term=x#use-configure-the-interface-x-components) does not. I used the suggestion to highlight the difference, but I didn't intend you to commit it 😅, so roll it back if you can please.

```suggestion
- **[Use & configure the Interface X Components](#use-configure-the-interface-x-components)** in
```

I just wanted to raise awareness between this differences between GitHub and EmpathyDocs markdown renderers.

2022-01-10 11:14 UTC, javieri-empathy commented on packages/x-components/static-docs/build-search-ui/README.md
> +- **[Use & configure the Interface X Components](#use--configure-the-interface-x-components)** in
I meant that this link won't work both in GitHub and EmpathyDocs at the same time. GitHub renders the id of the header with an extra `-` that [EmpathyDocs](https://docs.empathy.co/develop-empathy-platform/build-search-ui/?utm_term=x#use-configure-the-interface-x-components) does not. I used the suggestion to highlight the difference, but I didn't intend you to commit it 😅, so roll it back if you can please.

```suggestion
- **[Use & configure the Interface X Components](#use-configure-the-interface-x-components)** in
```

I just wanted to raise awareness between this differences between GitHub and EmpathyDocs markdown renderers.

2022-01-10 11:15 UTC, javieri-empathy approved these changes

2022-01-10 16:39 UTC, lydiafp requested changes

2022-01-19 09:17 UTC, lydiafp reviewed
Please see comments. There are few things that need to be changed

2022-02-07 11:15 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/README.md
> +- **[Use & configure the Interface X Components](#use-configure-the-interface-x-components)** in
Fixed

2022-02-07 11:15 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-x-components-integration-guide.md
>  [xPlugin configuration](#_3-configure-the-xplugin).
Fixed

2022-02-07 11:15 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-x-components-integration-guide.md
>     [Configure the search adapter](#_2-configure-the-search-adapter).
Fixed

2022-02-07 11:28 UTC, lydiafp approved these changes
@herrardo  - Changes approved!

2022-02-07 11:50 UTC, javieri-empathy approved these changes

2022-02-07 11:51 UTC, merged