feat(components): Add `payload` and `metadata` to the `SnippetCallbackExecuted` event payload.
empathyco/x pull request #315
Opened 2022-01-31 14:42 UTC by tajespasarela

EX-5324

Until now, the event  `SnippetCallbackExecuted`, emitted after a callback execution, only passed the event name and the callback return. But sometimes it's necessary also to know the original payload and metadata.

So this PR is to fix that.

2022-01-31 15:02 UTC, tiborux commented on packages/x-components/src/wiring/events.types.ts
>     * * Payload: An object containing the event that executed the callback and the callback result.
update the doc

```suggestion
   * * Payload: An object containing the event that executed the callback, the callback result the payload and the metadata.
```

2022-01-31 15:04 UTC, tiborux requested changes
<img src="https://media4.giphy.com/media/3oEjI5VtIhHvK37WYo/giphy.gif"/>

2022-02-01 08:08 UTC, javieri-empathy approved these changes

2022-02-01 08:09 UTC, tiborux approved these changes

2022-02-01 08:10 UTC, merged