feat(facets): add facets mixin to share logic between components
empathyco/x pull request #335
Opened 2022-02-17 09:48 UTC by tiborux

BREAKING-CHANGE: change the prop facetId to facetsIds in `selected-filters.vue` and `selected-filters-list.vue`, now it will be an array of facets ids instead of just one facet id.

EX-2899

## Motivation and context

We want to share logic between components that have repeated code. We saw that `selected-filters.vue` and `selected-filters-list.vue` have a prop `facetId` but in the other components is facetsIds, because in these other components we can use an array of facets ids instead just one. So to change that, we change the prop from facetId to facetsIds in those components that are receiving just one facetId to make them work with an array of facets ids. With this change we can reduce the code and share more logic between components.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [x] `Main`
- [ ] Other. Specify:

## How has this been tested?

Running the test and seeing how everything is still working.

2022-02-17 14:19 UTC, guillei10 approved these changes

2022-02-22 10:48 UTC, tajespasarela requested changes

2022-02-22 10:48 UTC, tajespasarela commented on packages/x-components/src/x-modules/facets/components/lists/__tests__/selected-filters-list.spec.ts
> +      props: ['facetsIds']
use `data` instead of props:
```javascript
      data() {
        return {
          facetsIds
        };
      }
```

2022-02-22 10:48 UTC, tajespasarela commented on packages/x-components/src/x-modules/facets/components/lists/__tests__/selected-filters-list.spec.ts
> +      propsData: {
remove this

2022-02-22 10:48 UTC, tajespasarela commented on packages/x-components/src/x-modules/facets/components/lists/__tests__/selected-filters-list.spec.ts
> +      template: '<SelectedFiltersList :facetsIds="facetsIds" />',
with the change up in the render function, you can remove this template here

2022-02-22 10:48 UTC, tajespasarela commented on packages/x-components/src/x-modules/facets/components/lists/__tests__/selected-filters-list.spec.ts
>      expect(selectedFiltersItems).toHaveLength(3);
remove the slot in line 113 since it is repeated, I don't know why

2022-02-22 10:48 UTC, tajespasarela commented on packages/x-components/src/x-modules/facets/components/lists/__tests__/selected-filters-list.spec.ts
> +    const selectedFiltersItems = selectedFiltersListWrapper.findAll(
move this to a function in the render API

2022-02-22 10:48 UTC, tajespasarela commented on packages/x-components/src/x-modules/facets/components/lists/__tests__/selected-filters.spec.ts
> +      props: ['facetsIds']
as in `selected-filters-list.spec` change this to `data`

2022-02-22 12:05 UTC, tiborux commented on packages/x-components/src/x-modules/facets/facets.mixin.ts
> +    return !isArrayEmpty(this.selectedFilters);
You are doing it in the `selectedFilters` computed, if there are facetsIds, we are adding selectFilters only for those that have selected Filters  ` [...selectedFilters, ...this.selectedFiltersByFacet[facetId]]`

2022-02-22 15:00 UTC, tajespasarela commented on packages/x-components/src/x-modules/facets/facets.mixin.ts
> +    return !isArrayEmpty(this.selectedFilters);
yes, you're right, I didn't see it correctly

2022-02-22 15:01 UTC, tajespasarela approved these changes

2022-02-24 09:39 UTC, guillei10 approved these changes

2022-02-24 09:40 UTC, merged