Feature/EX-5384: Add setSnippetConfig function in the API
empathyco/x pull request #358
Opened 2022-02-28 11:15 UTC by guillei10

EX-5384

Adding a `setSnippetConfig` function in the API in order to modify the `snippetConfig`. The implementation is found in the `XInstaller` but it gets exposed in the API throughout a facade. Also:

- Had to change the payload in the `ExtraParamsInitialized` to be a clone of the object instead. This avoids having this reference in the store, and we can change the `extraParams` properties without `Vuex` complaining.
- Changed the priority of how the `SnippetConfigExtraParams` adds properties in the `extraParams` object.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [ ] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [ ] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2022-03-01 08:10 UTC, javieri-empathy requested changes

2022-03-01 08:10 UTC, javieri-empathy commented on packages/x-components/src/x-installer/api/__tests__/default-api.spec.ts
> +  it('changes the `SnippetConfig` when calling the `setSnippetConfig` function', async () => {
I'm missing another test to ensure that non initial values get added reactively. For example, in this current test add the `store` attribute in another step.

2022-03-01 17:08 UTC, guillei10 commented on packages/x-components/src/x-installer/x-installer/x-installer.ts
> +      const snippetConfigObservable = this.snippetConfig;
I needed to access to the snippetConfig in the `provide` function below. Hmm not sure if there is a better way... I thought declaring the function outside the `new vue({...})` but then I had to type it.

2022-03-01 17:11 UTC, guillei10 commented on packages/x-components/src/x-modules/extra-params/components/snippet-config-extra-params.vue
> +      forEach({ ...this.values, ...snippetConfig }, (name, value) => {
Well we decided this with @tajespasarela, and it's more about what we want to give priority to. Without this change, the component props are always overriding whatever is coming from the snippetConfig. So the new `setSnippetConfig` has no effect if the value is already passed in the props of this component.

2022-03-01 17:12 UTC, guillei10 commented on packages/x-components/src/x-installer/x-installer/x-installer.ts
> +   */
Ups

2022-03-02 07:07 UTC, javieri-empathy commented on packages/x-components/src/x-modules/extra-params/components/snippet-config-extra-params.vue
> +      forEach({ ...this.values, ...snippetConfig }, (name, value) => {
Sold! I hadn't thought of simply calling the new function you just added.

2022-03-02 07:09 UTC, javieri-empathy commented on packages/x-components/src/x-installer/x-installer/x-installer.ts
> +      const snippetConfigObservable = this.snippetConfig;
I mean, why not just do this, without the `snippetConfigObservable` variable

```ts
this.snippetConfig = vue.observable(snippetConfig);
...
        provide() {
          return {
            snippetConfig: this.snippetConfig
          };
        },
...
```

2022-03-02 07:25 UTC, javieri-empathy submitted a review, later dismissed

2022-03-03 07:29 UTC, javieri-empathy approved these changes

2022-03-03 07:30 UTC, merged