Update static docs structure and information
empathyco/x pull request #368
Opened 2022-03-09 16:47 UTC by herrardo

…from development.

EX-5608

Change static docs structure to provide a better understanding to the developer user.

# Pull request template

The root document, README.md has been changed to provide two scenarios to the developer user:

- Integration
- Development

Currently, we have two sections explaining the integration by Archetype or by Components. But in both cases, we are talking about how to develop a search experience. So those two sections have been changed to use the word **_Develop_** instead.

We have added another section talking about integration to link a new document created by @javieri-empathy which is the documentation about integrating the archetype into a customer website in the same manner as we did for EmpathyX, loading the script and initialize the snippet.

I took advantage of this PR to also add information about the new feature added by @guillei10 `setSnippetConfig`and also to do a deeper explanation about callbacks and events to subscribe.

## Motivation and context
We haven't published the integration documentation in eDocs portal yet and some clients have asked about it.

- [ ] Dependencies. If any, specify:
- [x] Open issue. If applicable, link: EX-5608

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [x] Change requires a documentation update

## What is the destination branch of this PR?

- [x] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [x] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [x] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2022-03-10 09:32 UTC, herrardo commented
Corrected some warning and links too

2022-03-14 07:38 UTC, LuisMartinez15 requested changes
Good job! Doc is looking promising!

2022-03-14 07:38 UTC, LuisMartinez15 commented on packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md
> +| search           | - query (Optional) - The query to open Interface&nbsp;X with                   | Opens Interface&nbsp;X with the given search query.
```suggestion
| search           | - query (Optional) - The query to open Interface&nbsp;X with                   | Opens Interface&nbsp;X and triggers a search with the given query.                                                                                                               |
```

2022-03-14 07:38 UTC, LuisMartinez15 commented on packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md
> +| setSnippetConfig | - [Snippet Configuration](#snippet-configuration) - The Initialisation options | Changes the options and all components react to the changes. Helps to change, language, for insta
```suggestion
| setSnippetConfig | - [Snippet Configuration](#snippet-configuration) - The Initialisation options | Changes the options and all components react to the changes. Useful, for example, to change both search engine and displayed language without reloading the page. |
```

2022-03-17 11:17 UTC, LuisMartinez15 approved these changes
LGTM. Good job!

2022-03-23 10:54 UTC, mlcorton approved these changes
Great job, guys! Let's see how it shines in eDocs. Later on, I'll make a deeper rev and open a new PR if appropriate :)

2022-03-23 11:18 UTC, merged