[EX-5618] E2E tests maintenance
empathyco/x pull request #371
Opened 2022-03-15 16:43 UTC by mavmaf

## Motivation and context
The aim of this PR is to keep the E2E in shape. For this purpose, following changes where made:
 - Feature title change for` scroll.feature` file.
 - Several indentations were corrected.
 - Step added to `recommendation.feature` test.
 - Moving steps present on different tests to `common-steps.spec.ts`.
 - Removing steps present only in one feature file from `common-steps.spec.ts`.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?
- [ ] `Main`
- [ ] Other. Specify:

## How has this been tested?

You can run all tests with All.feature to check all of them still pass ;)

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [ ] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2022-03-16 11:22 UTC, javieri-empathy requested changes
Great job, nice homogeneisation.

2022-03-17 12:01 UTC, diegopf requested changes

2022-03-21 16:06 UTC, mavmaf commented on packages/x-components/tests/e2e/cucumber/keyboard-navigation/keyboard-navigation.spec.ts
> -Then('next element position is "{direction}"', (expectedPosition: Direction) => {
I roll up cable :D since if we change from `direction` to `string`, a random string out of those 4 defined won't make the test fail.

2022-03-22 09:31 UTC, diegopf commented on packages/x-components/tests/e2e/cucumber/common-steps.spec.ts
>    cy.getByDataTest('open-modal').click();
I'm not sure, I kind of prefer the current structure... seems more clean but I can see the benefit of not having all the step definitions globally. IMO I would do it on a different PR / task so we don't bother you too much on this PR. Let's see what @javieri-empathy thinks

2022-03-22 09:32 UTC, diegopf submitted a review, later dismissed

2022-03-22 21:20 UTC, javieri-empathy commented on packages/x-components/tests/e2e/cucumber/common-steps.spec.ts
>    cy.getByDataTest('open-modal').click();
Love it, I was just asking questions so we can plan future work (even if another developer had to do it), and you did most of the things already 😅.
We can discuss it in a future PR, and focus on the open topes for this one. My current opinion is that I would either have the `.feature` near its specific `.spec.ts`, or a separate parent folder for all the `.spec.ts` and `.feature` file. Nesting a single file in a directory like you propose with `each-spec-in-one-folder` seems redundant for me, but there might be a reason that I'd love to hear in **another PR** 😂.

2022-03-22 21:28 UTC, javieri-empathy requested changes
GJ, just a couple of messed imports and we should be fine to go.

2022-03-22 21:28 UTC, javieri-empathy commented on packages/x-components/tests/e2e/common/common-steps.spec.ts
> +import { PageableRequest } from '../../../../search-adapter/types/index';
Probably webstorm autoimport messed this import?
```suggestion
import { PageableRequest } from '@empathyco/x-adapter';
```

2022-03-22 21:28 UTC, javieri-empathy commented on packages/x-components/tests/e2e/filters/clear-filters.feature
> +
Remove additional blank line
```suggestion

```

2022-03-22 21:28 UTC, javieri-empathy commented on packages/x-components/tests/e2e/mocks/mocked-responses.spec.ts
> +} from '../../../../search-adapter/types/index';
```suggestion
} from '@empathyco/x-adapter';
```

2022-03-22 21:28 UTC, javieri-empathy commented on packages/x-components/tests/e2e/mocks/mocked-responses.spec.ts
> +} from '../../../src/__stubs__/index';
```suggestion
} from '../../../src/__stubs__';
```

2022-03-23 09:14 UTC, javieri-empathy approved these changes

2022-03-23 09:17 UTC, diegopf approved these changes

2022-03-23 09:19 UTC, merged