build(deps): Upgrade Cypress and Vue Cli plugins versions.
empathyco/x pull request #399
Opened 2022-04-01 07:04 UTC by tajespasarela

[EX-5417]

Since the VueCli versions were already updated, here it is only updated to a patch version. Also updated some cypress plugins.

2022-04-01 07:15 UTC, javieri-empathy requested changes

2022-04-01 07:15 UTC, javieri-empathy commented on packages/x-components/package.json
>      "@cucumber/cucumber": "~7.0.0-rc.0",
This dependency is not needed

2022-04-01 07:15 UTC, javieri-empathy commented on packages/x-components/package.json
> +    "@cypress/webpack-preprocessor": "~5.11.1",
This dependency is also not needed

2022-04-01 07:15 UTC, javieri-empathy commented on packages/x-components/package.json
>      "@cypress/browserify-preprocessor": "~3.0.1",
This dependency is also not needed

2022-04-01 07:15 UTC, javieri-empathy commented on packages/x-components/package.json
> +    "@vue/cli-service": "~4.5.17",
Shouldn't this be updated to the 5th version?

2022-04-04 09:01 UTC, LuisMartinez15 approved these changes
LGTM

2022-04-04 09:24 UTC, guillei10 approved these changes

2022-04-04 09:26 UTC, merged