feat(typeguards): add `isPath`
empathyco/x pull request #408
Opened 2022-04-04 14:05 UTC by LuisMartinez15

EX-5802

2022-04-04 15:07 UTC, tiborux submitted a review, later dismissed

2022-04-05 06:56 UTC, tajespasarela requested changes

2022-04-05 06:56 UTC, tajespasarela commented on packages/x-utils/src/__tests__/typeguards.spec.ts
> +    it('should return true when the passed path is a valid property path of the passed object', () => {
add an array example

2022-04-05 06:56 UTC, tajespasarela commented on packages/x-utils/src/typeguards.ts
> +  return getSafePropertyChain<ExtractType<SomeObject, Path>>(obj, path) !== undefined
this can be simplify by returning `getSafePropertyChain<ExtractType<SomeObject, Path>>(obj, path) !== undefined`

2022-04-05 08:08 UTC, tajespasarela approved these changes

2022-04-05 08:18 UTC, tiborux approved these changes

2022-04-05 08:18 UTC, merged