feat(search): add Banner component
empathyco/x pull request #42
Opened 2021-07-12 12:34 UTC by tiborux

### Description

Adds the Banner component

### Test

Add the example into a view and check that everything is working fine.

2021-07-12 13:51 UTC, javieri-empathy commented on packages/x-components/src/x-modules/search/components/banner.vue
> +   * something. Usually it is the first item in the grid or it can be placed in the middle of them
The only thing I can complain is the `,` in the next line

2021-07-12 13:53 UTC, javieri-empathy requested changes
Virtually approved, just the `,` issue

2021-07-13 09:09 UTC, javieri-empathy approved these changes

2021-07-13 10:26 UTC, davidmfempathy approved these changes

2021-07-13 10:27 UTC, merged