feat(schemas): make schemas mutables [EX-5435]
empathyco/x pull request #424
Opened 2022-04-13 08:45 UTC by diegopf

## Motivation and context
Create a new type MutableSchema and a function makeSchemaMutable that allows to create a new MutableSchema from a Schema. MutableSchemas have two additionally methods that allow us to either replace or override the original schema.

- [ ] Dependencies. If any, specify:
- [x] Open issue. If applicable, link:  [EX-5435](https://searchbroker.atlassian.net/browse/EX-5435)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [x] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [x] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [x] I have performed a **self-review** on my own code.
- [x] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [x] My changes generate **no new warnings**.
- [x] I have added **tests** that prove my fix is effective or that my feature works.
- [x] New and existing **unit tests pass locally** with my changes.

2022-04-18 07:43 UTC, diegopf commented on packages/x-adapter/src/mappers/schema-mapper.factory.ts
> +  schema: Schema<Source, Target> | MutableSchema<Schema<Source, Target>>
Good point, you are right! At some point during development was needed but seems it is not anymore.

2022-04-18 12:42 UTC, LuisMartinez15 requested changes
good job!

2022-04-18 12:42 UTC, LuisMartinez15 commented on packages/x-adapter/src/schemas/schemas.types.ts
> +   * Allows to create a new {@link Schema | schema} using the original one as starting point.
```suggestion
   * Create a new {@link Schema | schema} using the original one as starting point.
```

2022-04-18 12:42 UTC, LuisMartinez15 commented on packages/x-adapter/src/schemas/schemas.types.ts
> + */
```suggestion
/**
 * A {@link Schema | schema} with extended functionality to: completely replace
 * the original schema, partially override it or create a new one.
 *
 * @param OriginalSchema - The {@link Schema | schema} that will be mutable.
 *
 * @public
 */
```

2022-04-18 13:44 UTC, diegopf commented on packages/x-adapter/src/schemas/utils.ts
> +        delete this[key];
Funny, I discussed the same thing with @tajespasarela. IMO I prefer the early return approach and avoid having the conditional clause negative.

2022-04-18 13:46 UTC, diegopf commented on packages/x-adapter/src/schemas/utils.ts
> +export const mutableSchemasInternalMethods = ['$replace', '$override', '$extends'];
You are right! Previously I was using it on another place but now does not make sense to export it. However I'd like to keep the const IMO makes the code more readable.

2022-04-18 13:56 UTC, diegopf commented on packages/x-adapter/src/schemas/schemas.types.ts
> +   * Allows to create a new {@link Schema | schema} using the original one as starting point.
Sounds good to me

2022-04-18 13:56 UTC, diegopf commented on packages/x-adapter/src/schemas/utils.ts
> +export function makeSchemaMutable<T extends Schema>(schema: T): MutableSchema<T> {
Sounds good to me

2022-04-18 15:23 UTC, tajespasarela requested changes

2022-04-18 15:23 UTC, tajespasarela commented on packages/x-adapter/src/schemas/utils.ts
> +    $toString: function (includeInternalMethods = false) {
rename to standard `toString` to coercing directly to a string:

`console.log(schema)`

2022-04-19 06:35 UTC, tajespasarela requested changes

2022-04-19 06:35 UTC, tajespasarela commented on packages/x-adapter/src/schemas/utils.ts
> +      return serialize(this, !!includeInternalMethods);
you can remove the `!!`

2022-04-19 07:12 UTC, tajespasarela approved these changes

2022-04-19 07:30 UTC, LuisMartinez15 approved these changes
good job! 👏🏿

2022-04-19 07:33 UTC, merged