test(component): configure Cypress component testing
empathyco/x pull request #44
Opened 2021-07-13 10:47 UTC by javieri-empathy

# Description

Configures [Cypress component testing](https://docs.cypress.io/guides/component-testing/introduction#What-is-Component-Testing) for the x-components project. To do so, the following changes have been made:

- Separate Cypress e2e & unit tests in different folders
- Remove unnecessary `webpack.config.js`. Cypress has now support by default for TypeScript, and cucumber can be configured easily in other way.
- Adjust paths

# Context

Some things can't be tested with jest and JSDOM, we need to have a real browser environment to properly test them. One of this examples is the infinite scroll.

# Test

Nothing has broken, and you can run the new cypress component tests properly

2021-07-13 12:39 UTC, tiborux requested changes

2021-07-13 12:39 UTC, tiborux commented on packages/x-components/package.json
>      "test:unit": "vue-cli-service test:unit",
We should remove the old one?

2021-07-13 12:39 UTC, tiborux commented on packages/x-components/tests/unit/test.spec.ts
> +describe('Sample test file', () => {
Is this necessary? I mean its just an example right?

2021-07-14 11:40 UTC, davidmfempathy approved these changes

2021-07-14 12:25 UTC, tiborux approved these changes

2021-07-14 12:26 UTC, merged