feat(theme): add custom default values
empathyco/x pull request #451
Opened 2022-04-25 11:51 UTC by LuisMartinez15

EX-5717

Add custom default values to the plugin's `theme`

2022-04-27 07:45 UTC, diegopf requested changes
I see on figma that there are defined highlight colors but missing here. Do we need them?

2022-04-27 09:17 UTC, LuisMartinez15 commented
@diegopf Those were added afterwards by Cristina and she didn't tell me 😞 

Thanks for pointing it out, tho. I'll include them.

2022-04-27 11:32 UTC, diegopf approved these changes

2022-04-29 08:06 UTC, tiborux approved these changes
<img src="https://media3.giphy.com/media/3o72FcJmLzIdYJdmDe/giphy.gif"/>

2022-04-29 08:07 UTC, merged