ci: Fix publishing in x-components. Normalize build scripts.
empathyco/x pull request #46
Opened 2021-07-15 08:56 UTC by javieri-empathy

# Description

Tries to fix the publishing x components issue, and normalises the package json scripts.

2021-07-15 09:06 UTC, javieri-empathy commented on packages/get-safe-property-chain/package.json
> +    "postinstall": "npm run build",
Lerna says that it invokes, `prepublish`, and `prepare` commands after a CI, but the problem with those commands is that `prepublish` is deprecated, and both of them are also invoked by npm before the `npm pack` command. So i chose to use `postinstall` and `prepublishOnly`.

2021-07-15 13:11 UTC, LuisMartinez15 approved these changes
The flow seems to be working as expected.

2021-07-16 06:23 UTC, pmareke requested changes
I can't see the `.tgz` file for the eslint plugin:

![image](https://user-images.githubusercontent.com/3502075/125901871-054b36c9-89c5-4b38-9862-b8936c1c5e5c.png)

2021-07-16 06:23 UTC, pmareke commented on packages/deep-merge/package.json
> -    "prebuild": "npm run clean && npm run lint && echo Using TypeScript && tsc --version",
This `npm run lint` that you remove when it's invoked now?

2021-07-16 06:32 UTC, pmareke approved these changes
LGTM

2021-07-16 06:33 UTC, merged