feat(facets): expose `clickEvents` as a `prop` in filters components using a `RenderlessFilter`
empathyco/x pull request #463
Opened 2022-04-28 16:30 UTC by LuisMartinez15

EX-5986

Exposed `@Prop() clickEvents` in filters component using a `RenderlessFilter` so the events emitted on clicked are configurable.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## How has this been tested?

Added new unit test cases.

## Checklist:

- [x] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [x] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [x] My changes generate **no new warnings**.
- [x] I have added **tests** that prove my fix is effective or that my feature works.
- [x] New and existing **unit tests pass locally** with my changes.

2022-04-29 10:31 UTC, CachedaCodes requested changes

2022-05-02 06:15 UTC, LuisMartinez15 commented on packages/x-components/src/x-modules/facets/components/filters/hierarchical-filter.vue
> +      }, {} as Partial<XEventsTypes>);
You're right. Totally forgot about `Object.entries`, thanks!

2022-05-02 06:55 UTC, LuisMartinez15 commented on packages/x-components/src/x-modules/facets/components/filters/hierarchical-filter.vue
> +    public clickEvents!: Partial<XEventsTypes>;
Indeed. I forgot to update the documentation 🤦🏿

2022-05-04 08:01 UTC, mnavarroespinosa approved these changes
Looks good to me!

2022-05-05 07:31 UTC, tiborux commented on packages/x-components/src/x-modules/facets/components/filters/simple-filter.vue
> +</template>
Complete this example with the <script> section, we want to have examples that you can copy and paste. :kekw:

2022-05-05 07:36 UTC, tiborux commented on packages/x-components/src/x-modules/facets/components/filters/__tests__/hierarchical-filter.spec.ts
> +          :clickEvents="clickEvents"
adding the prop here is not neccesary, you are not using it.

2022-05-05 07:37 UTC, tiborux commented on packages/x-components/src/x-modules/facets/components/filters/__tests__/hierarchical-filter.spec.ts
> +        <HierarchicalFilter :filter="filter" :clickEvents="clickEvents">
Same here

2022-05-05 07:37 UTC, tiborux commented on packages/x-components/src/x-modules/facets/components/filters/__tests__/hierarchical-filter.spec.ts
> +          <HierarchicalFilter :filter="filter" :clickEvents="clickEvents" #label="{ filter }">
Same here

2022-05-05 11:15 UTC, tiborux approved these changes

2022-05-05 11:16 UTC, CachedaCodes approved these changes

2022-05-05 11:16 UTC, merged