docs: remove Guille Iglesias from core team
empathyco/x pull request #477
Opened 2022-05-09 09:56 UTC by herrardo

EX-6048

Fix links and update roadmap
# Pull request template
 
Describe the purpose of the change, the specific changes done in detail, and the issue you have fixed.

## Motivation and context
Keep the roadmap up to date to give visibility to external devs

- [ ] Dependencies. If any, specify:
- [x] Open issue. If applicable, link: EX-6048

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [x] Change requires a documentation update

## What is the destination branch of this PR?

- [x] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [x] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [x] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2022-05-09 11:29 UTC, mlcorton requested changes
Everything is OK except for one link which is outdated. 

- [ ] In line 74, please update architecture link to: `- [Interface X architecture](https://docs.empathy.co/develop-empathy-platform/build-search-ui/web-x-architecture/)`

2022-05-09 17:26 UTC, herrardo commented
> Everything is OK except for one link which is outdated.
> 
> * [x]  In line 74, please update architecture link to: `- [Interface X architecture](https://docs.empathy.co/develop-empathy-platform/build-search-ui/web-x-architecture/)`

Fixed!

2022-05-10 06:59 UTC, mlcorton approved these changes

2022-05-10 09:55 UTC, CachedaCodes approved these changes

2022-05-10 09:56 UTC, merged