feat: add initial implementation
empathyco/x pull request #506
Opened 2022-05-25 13:52 UTC by BrunoRodrigues1999

**Purpose**
Create a new Highlight component to be in charge of highlighting the part of a suggestions that matches the current query in the search box.

## Motivation and context
Extract the highlight logic from the [BaseSuggestion](https://github.com/empathyco/x/blob/main/packages/x-components/src/components/suggestions/base-suggestion.vue) component.

The methods needed for the highlight funcionality were extracted from the [BaseSuggestion](https://github.com/empathyco/x/blob/main/packages/x-components/src/components/suggestions/base-suggestion.vue) and moved into a ```Highlight``` component

- [ ] Dependencies. If any, specify: None
- [ ] Open issue: **[issue] (https://github.com/empathyco/x/issues/381)

## Type of change
New feature 

## What is the destination branch of this PR?
Main

## How has this been tested?
The component codebase was tested from a static analysis point of view since we couldn't find the highlight functionality in the UI itself.

## Checklist:

- [x] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [x] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [x] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2022-06-08 12:57 UTC, diegopf requested changes
I think there was a little bit of confusion with the prop names 😅.  Please, add comments to class methods.  We should also take a look at [base-suggestion.spec.ts](https://github.com/empathyco/x/blob/main/packages/x-components/src/components/suggestions/__tests__/base-suggestions.spec.ts) tests and move the related ones to a new testing file for this component.

Thanks for the contribution! :)

2022-06-08 12:57 UTC, diegopf commented on packages/x-components/src/components/highlight/highlight.vue
> +    protected toHighlight!: string;
```suggestion
    protected textToHighlight!: string;
```

2022-06-08 12:57 UTC, diegopf commented on packages/x-components/src/components/highlight/highlight.vue
> +    protected highlight!: string;
```suggestion
    protected textToMatch!: string;
```

2022-06-08 12:57 UTC, diegopf commented on packages/x-components/src/components/highlight/highlight.vue
> +      return !!this.toHighlight && normalizeString(this.toHighlight).includes(this.toHighlight);
```suggestion
      return !!this.textToMatch && normalizeString(this.textToHighlight).includes(this.textToMatch);
```

2022-06-08 12:57 UTC, diegopf commented on packages/x-components/src/components/highlight/highlight.vue
> +        const matcherIndex = normalizeString(this.highlight).indexOf(this.toHighlight);
```suggestion
        const matcherIndex = normalizeString(this.textToHighlight).indexOf(this.textToMatch);
```

2022-06-08 12:57 UTC, diegopf commented on packages/x-components/src/components/highlight/highlight.vue
> +    class="x-suggestion__query"
```suggestion
    class="x-highlight"
```

2022-07-25 09:48 UTC, herrardo commented
@BrunoRodrigues1521 @BrunoRodrigues1999 @jtomasdias00  This PR is waiting for your update, could you have a look?

2022-09-05 08:32 UTC, herrardo requested changes
@BrunoRodrigues1521 @BrunoRodrigues1999 @jtomasdias00 Last call to review&update this PR :)

2022-09-15 09:55 UTC, closed without merging