refactor: recommendations in platform adapter
empathyco/x pull request #538
Opened 2022-06-10 12:07 UTC by ajperezbau

EX-6309

2022-06-10 12:25 UTC, diegopf requested changes

2022-06-10 12:25 UTC, diegopf commented on packages/x-adapter-platform/src/mappers/requests/index.ts
> +export * from './recommendations-request.mapper';
Please, add the missing exports

2022-06-10 12:25 UTC, diegopf commented on packages/x-adapter-platform/src/types/requests/index.ts
> +export * from './recommendations-request.model';
Please, add the next-queries-request.model

2022-06-10 12:25 UTC, diegopf commented on packages/x-adapter-platform/src/types/responses/index.ts
> +export * from './recommendations-response.model';
Please, add the next-queries-response.model

2022-06-13 06:44 UTC, tiborux commented on packages/x-adapter-platform/src/schemas/responses/index.ts
> +export * from './recommendations-response.schema';
Add popular searches here

2022-06-13 06:47 UTC, tiborux requested changes
gj

2022-06-13 07:44 UTC, diegopf submitted a review, later dismissed

2022-06-13 09:58 UTC, mnavarroespinosa approved these changes
looks good to me! gj!

2022-06-13 10:39 UTC, tiborux approved these changes

2022-06-13 11:12 UTC, mnavarroespinosa approved these changes

2022-06-13 11:13 UTC, tiborux approved these changes

2022-06-13 11:35 UTC, diegopf approved these changes

2022-06-13 11:36 UTC, merged