feat(search-box): add blacklistedCharacters prop
empathyco/x pull request #573
Opened 2022-06-22 13:23 UTC by alonsogarciapablo

# Pull request template
 
Describe the purpose of the change, the specific changes done in detail, and the issue you have fixed.

## Motivation and context

- [ ] Dependencies. If any, specify:
- [ ] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [ ] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [ ] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2022-09-16 09:34 UTC, tiborux commented on packages/x-components/src/x-modules/search-box/components/search-input.vue
> +    protected filterBlacklistedCharacters(event: InputEvent): void {
We are not filtering the values, instead, we are "blocking" them. So, i will name it like:

`blockBlacklistedCharacters`, `avodiBlacklistedCharacters`, `preventBlacklistedCharacters`

what do you think?

2022-09-16 09:59 UTC, tiborux commented on packages/x-components/src/x-modules/search-box/components/__tests__/search-input.spec.ts
> +    function itBlacklists(characters: string[]): void {
```suggestion
    function hasBeenBlackListed(characters: string[]): void {
```

2022-09-16 10:00 UTC, tiborux commented on packages/x-components/src/x-modules/search-box/components/__tests__/search-input.spec.ts
> +    describe(`with default blacklisted characters '<>'`, () => {
```suggestion
    it(`should blacklist the default chars'<>'`, () => {
```

2022-09-16 10:01 UTC, tiborux commented on packages/x-components/src/x-modules/search-box/components/__tests__/search-input.spec.ts
> +    describe(`with custom blacklisted characters '${blacklistedCharacters}'`, () => {
```suggestion
    it(`should blacklist the characters '${blacklistedCharacters}' passed by prop`, () => {
```

2022-09-16 11:42 UTC, tiborux commented on packages/x-components/src/x-modules/search-box/components/__tests__/search-input.spec.ts
> +  describe('input sanitization', () => {
What do you think if we follow this approach? We reduce a lot of the code:

```
 describe('input sanitization', () => {
    function dispatchEvent(data: string): InputEvent {
      const event = new InputEvent('beforeinput', { data });
      event.preventDefault = jest.fn();
      input.dispatchEvent(event);
      return event;
    }

    function checkCharacterPrevention(characters: string[], applyBlackList: boolean): void {
      characters.forEach((character: string) => {
        // eslint-disable-next-line @typescript-eslint/unbound-method
        const event = dispatchEvent(character).preventDefault;
        if (applyBlackList) {
          expect(event).toHaveBeenCalled();
        } else {
          expect(event).not.toHaveBeenCalled();
        }
      });
    }

    it(`should blacklist default characters '<>'`, () => {
      expect.hasAssertions();
      checkCharacterPrevention(['<', '>'], true);
      checkCharacterPrevention(['a', 'b', '2', '+'], false);
    });

    it('should blacklist the characters send by prop', () => {
      expect.hasAssertions();
      const blacklistedCharacters = 'a1+$#';
      input = mountNewSearchInput({
        blacklistedCharacters: blacklistedCharacters
      }).input;

      checkCharacterPrevention(blacklistedCharacters.split(''), true);
      checkCharacterPrevention(['b', '2', '>', '<'], false);
    });
    ```

2022-09-16 11:44 UTC, tiborux requested changes
Gj

2022-09-19 08:30 UTC, mnavarroespinosa requested changes
gj!

2022-09-19 08:30 UTC, mnavarroespinosa commented on packages/x-components/src/x-modules/search-box/components/search-input.vue
> +    :blacklistedCharacters="0123456789"
This could not be a number
```suggestion
    blacklistedCharacters="0123456789"
```

2022-09-19 10:10 UTC, mnavarroespinosa commented on packages/x-components/src/views/home/Home.vue
> +            id="searchInput.blackListedCharacters"
```suggestion
            id="searchInput.blacklistedCharacters"
```

2022-10-19 12:17 UTC, herrardo commented
Hi @alonsogarciapablo !

This was solved in this [previous commit](https://github.com/empathyco/x/commit/afc865f2e13d775e5ee4a602536dfd2ee8b474b8)


Thanks!

2022-10-19 12:17 UTC, closed without merging