feat(components): add `BaseSwitch` component.
empathyco/x pull request #586
Opened 2022-07-05 11:13 UTC by javieri-empathy

EX-6004

Adds the `BaseSwitch` component.

- Does not handle its own selected state
- Supports v-model
- 3 sizes (default, sm and lg). This sizes use the closest token values
- Uses CSS variables internally to simplify styling size and background

To test it you can replace the checkbox control of the `Home.vue` **instant search** with the new switch component:

```html
      <li class="x-test-controls__item x-list__item">
        <label>
          search-input - instant
          <BaseSwitch v-model="controls.searchInput.instant" id="search-input-is-instant" />
        </label>
      </li>
```

2022-07-05 12:10 UTC, LuisMartinez15 requested changes
good job!

2022-07-05 12:10 UTC, LuisMartinez15 commented on packages/x-components/src/components/base-switch.vue
> +change:
```suggestion
The switch component also supports v-model syntax to automatically handle its state
change:
```

2022-07-05 12:10 UTC, LuisMartinez15 commented on packages/x-components/src/components/base-switch.vue
> +   * its selected state using a prop, and emits an event whenever the user
Maybe we should specify that the emitted event is an internal (`Vue`) event and not an `XEvent` (which is later specify in the `<docs>` section).

2022-07-05 13:06 UTC, tiborux commented on packages/x-components/src/components/base-switch.vue
> +  <BaseSwitch :value="value" @change="value = !value" />
Linter prefers a different order 🎃 

```suggestion
  <BaseSwitch @change="value = !value" :value="value" />
```

2022-07-05 13:15 UTC, tiborux requested changes
gj

2022-07-05 14:24 UTC, javieri-empathy commented on packages/x-components/src/components/base-switch.vue
> +  import { VueCSSClasses } from '../utils';
Fuck imports, thanks for notising it.

2022-07-06 06:45 UTC, tiborux approved these changes

2022-07-06 07:11 UTC, LuisMartinez15 approved these changes
gj!

2022-07-06 07:20 UTC, merged