feat: add settings icon
empathyco/x pull request #589
Opened 2022-07-06 06:18 UTC by ajperezbau

EX-6519

2022-07-06 07:36 UTC, tiborux commented on packages/x-components/src/components/icons/settings.vue
> +    <g fill="none" fill-rule="evenodd">
you can remove the group <g>

2022-07-06 07:36 UTC, tiborux commented on packages/x-components/src/components/icons/index.ts
> +export { default as SettingsIcon } from './settings.vue';
Sort it alphabetically

2022-07-06 07:37 UTC, tiborux requested changes
gj

2022-07-06 07:59 UTC, diegopf requested changes

2022-07-06 12:31 UTC, diegopf approved these changes

2022-07-07 06:59 UTC, tiborux approved these changes

2022-07-07 06:59 UTC, merged