Bugfix/ex 6457 allow extending all transitions
empathyco/x pull request #600
Opened 2022-07-13 09:59 UTC by javieri-empathy

There were 2 issues before this PR:
- Directional animations (like translate) didn't support extra `$listeners`.
- There was a trick that relied on adding beforeLeave and afterLeave hooks to the transition component so we could delay the overlay animation, but this only worked for the leaving transition

Knowing that, this PR implements following changes:
* Normalises all animation components, so they can both receive extra listeners and props
* Fixes modal open/close logic so it can support independent animations for both the content and the overlay.
* Adds CSS variables for opacity and overlay color (so we can stop using `!important` in clients to override it.
* Adds a `Fade` animation, used by default for the overlay.

2022-07-14 08:31 UTC, LuisMartinez15 requested changes
Why are we setting different values to `inheritAttrs` but always binding them to the root element?

2022-07-14 08:31 UTC, LuisMartinez15 commented on packages/x-components/src/components/animations/collapse-width.vue
>      mixins: [createCollapseAnimationMixin('width')]
Shouldn't we add `inheritAttrs` here too?

```suggestion
    mixins: [createCollapseAnimationMixin('width')],
    inheritAttrs: true
```

2022-07-14 08:31 UTC, LuisMartinez15 commented on packages/x-components/src/components/animations/fade.vue
> +      <p v-if="open">León is southern Spain</p>
```suggestion
      <p v-if="shouldRender">León is southern Spain</p>
```

2022-07-14 13:05 UTC, javieri-empathy commented on packages/x-components/src/components/animations/fade.vue
> +      <p v-if="open">León is southern Spain</p>
Vaya ojo vida TQ+ (What eye life LY+)

2022-07-15 06:46 UTC, LuisMartinez15 approved these changes
good job!

2022-07-15 07:01 UTC, CachedaCodes approved these changes

2022-07-15 07:02 UTC, merged