feat(e2e): check that search modal will open again after close it the first. time
empathyco/x pull request #613
Opened 2022-07-20 11:39 UTC by tiborux

EX-6708

2022-07-20 12:07 UTC, LuisMartinez15 approved these changes
good job!

2022-07-21 07:50 UTC, CachedaCodes requested changes

2022-07-21 07:50 UTC, CachedaCodes commented on packages/x-components/tests/e2e/common/common-steps.spec.ts
> +When('close button is clicked', () => {
Clarify the button because it's in the common steps and is not any button

```suggestion
When('close modal button is clicked', () => {
```

2022-07-21 08:29 UTC, LuisMartinez15 approved these changes

2022-07-21 09:06 UTC, merged