feat: emit event to confirm disabling history queries if the list is empty
empathyco/x pull request #615
Opened 2022-07-21 11:13 UTC by ajperezbau

EX-6696

2022-07-21 12:43 UTC, LuisMartinez15 requested changes
good job!

2022-07-21 12:43 UTC, LuisMartinez15 commented on packages/x-components/src/x-modules/history-queries/components/__tests__/history-queries-switch.spec.ts
> +    expect(listener).toHaveBeenCalledTimes(1);
Can you also check the `isEnabled` flag in the `store` `state`?

```suggestion
  await new Promise(resolve => setTimeout(resolve));

  expect(wrapper.vm.$store.state.x.historyQueries.isEnabled).toBe(false);
  expect(listener).toHaveBeenCalledTimes(1);
```

2022-07-22 07:57 UTC, LuisMartinez15 approved these changes
good job!

2022-07-22 08:02 UTC, tiborux approved these changes

2022-07-22 09:54 UTC, merged