feat(next-queries): add next query preview component
empathyco/x pull request #631
Opened 2022-07-28 12:22 UTC by ajperezbau

EX-6646

2022-07-29 09:19 UTC, annacv approved these changes

2022-08-01 09:19 UTC, tajespasarela requested changes

2022-08-01 09:19 UTC, tajespasarela commented on packages/x-components/src/views/home/Home.vue
> +    max-width: 180px !important;
inline the styles in the element, no need to add more complex CSS for this view:

`style="max-width: 180px"`

2022-08-01 09:19 UTC, tajespasarela commented on packages/x-components/src/x-modules/next-queries/components/next-query-preview.vue
> +```vue live
add also an example of the new slot

2022-08-03 09:23 UTC, tajespasarela approved these changes

2022-08-04 06:22 UTC, annacv approved these changes

2022-08-04 06:23 UTC, merged