Create archetype utils package
empathyco/x pull request #701
Opened 2022-09-06 09:46 UTC by annacv

EX-6930

2022-09-06 10:14 UTC, herrardo requested changes

2022-09-06 10:14 UTC, herrardo commented on packages/x-archetype-utils/README.md
> +# x-archetype-utils
```suggestion
# x-archetype-utils

`x-archetype-utils` is a library that provides utilities to ease development. It's used in the [Interface X Archetype](https://github.com/empathyco/x-archetype) project. 

## Contributing

To start contributing to the project, please take a look at our [Contributing Guide](https://github.com/empathyco/x/blob/main/.github/CONTRIBUTING.md).
```

2022-09-06 10:30 UTC, tiborux commented on packages/x-archetype-utils/jest.config.js
> +  transform: {
Is there a real difference between using the `preset: 'ts-jest'` or using transform for just *.ts files?

Should we change the `testEnvironment` to `jsdom`?

2022-09-06 10:54 UTC, tiborux commented on packages/x-archetype-utils/src/__tests__/sample.spec.ts
> +it('should ', function () {
```suggestion
it('should ', () => {
```

2022-09-06 11:03 UTC, tiborux commented on packages/x-archetype-utils/jest.config.js
> +  transform: {
As javi said, use the preset

2022-09-06 11:05 UTC, tiborux commented on packages/x-archetype-utils/package.json
> +    "build:cjs": "node_modules/.bin/tsc --project tsconfig.cjs.json",
Remove node_modules part in all builds

```suggestion
    "build:cjs": "tsc --project tsconfig.cjs.json",
```

2022-09-07 06:52 UTC, tiborux commented
Just a comment, you should wait until you have 2 reviewers that already post comments to apply the changes. Sometimes some of the comments can be wrong or can be discussed between the reviewers and the owner of the pr

2022-09-07 06:52 UTC, tiborux submitted a review, later dismissed

2022-09-07 09:53 UTC, diegopf requested changes

2022-09-07 09:53 UTC, diegopf commented on packages/x-archetype-utils/package.json
> +    "test": "node_modules/.bin/jest",
```suggestion
    "test": "jest",
```

2022-09-07 10:07 UTC, diegopf approved these changes

2022-09-07 10:34 UTC, herrardo approved these changes

2022-09-07 10:38 UTC, tiborux approved these changes

2022-09-07 10:41 UTC, merged