feat(components): add disable animation mixin
empathyco/x pull request #703
Opened 2022-09-07 10:14 UTC by tiborux

EX-6838

2022-09-07 14:28 UTC, mnavarroespinosa submitted a review, later dismissed
good job!

2022-09-08 06:18 UTC, javieri-empathy requested changes

2022-09-08 06:18 UTC, javieri-empathy commented on packages/x-components/src/components/animations/disable-animation.mixin.ts
> +  protected get name(): string {
Where is the test? :golpederemo:

2022-09-08 06:18 UTC, javieri-empathy commented on packages/x-components/src/components/animations/disable-animation.mixin.ts
> +export class DisableAnimationMixin extends Vue {
Export the mixin

2022-09-08 13:11 UTC, mnavarroespinosa requested changes
The build seems to be failing because of a JSDoc in `disable-animation.mixin.ts`.

![image](https://user-images.githubusercontent.com/77450928/189130305-639c1ebf-cf89-48b4-83ee-3d222fa3d3eb.png)
 
Maybe you can define it as:

```
  /**
   * The animation's name based on the {@link DisableAnimationMixin.disableAnimation} flag.
   *
   * @returns The animation name.
   * @internal
   */
```

2022-09-08 14:09 UTC, mnavarroespinosa approved these changes

2022-09-09 08:50 UTC, javieri-empathy approved these changes

2022-09-09 08:50 UTC, merged