feat: make adapter configurable in home view
empathyco/x pull request #750
Opened 2022-09-29 07:00 UTC by diegopf

EX-7073

The `e2eAdapter` can't be used outside cypress directly. This adapter makes requests that cypress will intercept and resolve with mocked data. In order to workaround this issue, in this PR I prevent the `e2eAdapter` from using the [mockedFetchHttpClient](https://github.com/empathyco/x/blob/feature/EX-7072-make-adapter-configurable-in-home-view/packages/x-components/src/adapter/e2e-adapter.ts#L12) if we are not in a cypress environment and return the mocked data instead.

Note: if you see an error regarding the `SlidingQueryPreview` complaining about the missing location, this will be fixed in #746

2022-09-29 11:11 UTC, CachedaCodes requested changes

2022-10-03 08:59 UTC, LuisMartinez15 submitted a review, later dismissed
good job!

2022-10-03 11:18 UTC, CachedaCodes approved these changes

2022-10-03 11:20 UTC, LuisMartinez15 approved these changes

2022-10-03 11:33 UTC, merged