feat: improve documentation in x-tailwind plugin
empathyco/x pull request #756
Opened 2022-10-04 09:51 UTC by CachedaCodes

EX-7129

## Motivation and context
Plugin creation function wasn't very clear without documentation, so one was added.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [X] Change requires a documentation update

## What is the destination branch of this PR?

- [X] `Main`
- [ ] Other. Specify:

2022-10-05 07:44 UTC, LuisMartinez15 requested changes
good job!

2022-10-05 07:44 UTC, LuisMartinez15 commented on packages/x-tailwindcss/src/x-tailwind-plugin/plugin.ts
> +     * the color, spacing, etc. Of the styles generated in this step.
```suggestion
     * Registers the generated CSS for the components and utilities of the plugin to the
     * respective Tailwind layer. It depends on the plugin's theme, affecting
     * the color, spacing, etc... of the styles generated in this step.
```

2022-10-05 10:22 UTC, ajperezbau approved these changes
Nice 👌

2022-10-05 10:28 UTC, LuisMartinez15 approved these changes

2022-10-06 07:46 UTC, diegopf approved these changes

2022-10-06 07:46 UTC, merged