Test/ex 6848 next queries preview tests
empathyco/x pull request #759
Opened 2022-10-06 08:47 UTC by mavmaf

# Pull request template
 
Describe the purpose of the change, the specific changes done in detail, and the issue you have fixed.

## Motivation and context

- [ ] Dependencies. If any, specify:
- [ ] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [ ] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [ ] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2022-10-12 08:22 UTC, tiborux commented on packages/x-components/tests/e2e/next-queries-preview.feature
> +Feature: Next queries preview component
Should we add a case when you click the query of the next query? Because right now the query can be clicked and set the search query.

2022-10-12 08:22 UTC, tiborux requested changes
gj

2022-10-12 12:18 UTC, CachedaCodes requested changes

2022-10-17 07:31 UTC, CachedaCodes approved these changes

2022-10-17 07:42 UTC, tiborux approved these changes

2022-10-17 07:42 UTC, merged