Docs/edoc 2038 query preview proofreading
empathyco/x pull request #805
Opened 2022-10-27 12:12 UTC by mlcorton

# Pull request template
Reviewed doc about the new Query Preview feature that was recently added and approved without prior TW check and based on the comments from https://github.com/empathyco/docs-empathy-documentation/pull/692/files

## Motivation and context
Meet docs style and tone of voice. Improve readability, understanding, and page navigation.

- [ ] Dependencies. If any, specify:
- [ ] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [X] Change requires a documentation update

## What is the destination branch of this PR?

- [X] `Main`
- [ ] Other. Specify:

## How has this been tested?

Content has already been tested and previewed in EPDocs portal locally.

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [X] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2022-10-27 13:28 UTC, herrardo requested changes

2022-10-27 13:28 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md
> +- Notes on how to set up [** the preview of query results**](#dynamic-query-results-preview) for determined queries at the pre-search stage
```suggestion
- Notes on how to set up [**the preview of query results**](#dynamic-query-results-preview) for
  determined queries at the pre-search stage
```

2022-10-27 13:28 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md
> +The following example shows you how to change dynamically the preview of query results in the _kids_ and _adult_ sections:
```suggestion
The `queriesPreview` parameter settings can be changed to dynamically preview product results from
the queries you define according to your brand's strategy. Use the `setSnippetConfig` function in
the [`X API`](#x-api) object to determine the queries to be previewed dynamically depending on the
section the shopper is visiting in your commerce store, for instance, or any other scenario.

The following example shows you how to change dynamically the preview of query results in the _kids_
and _adult_ sections:
```

2022-10-27 13:28 UTC, herrardo commented on packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md
> +### Dynamic query results preview
Don't you like better the original title?

2022-10-27 14:39 UTC, herrardo approved these changes

2022-11-02 13:18 UTC, mnavarroespinosa approved these changes

2022-11-02 13:19 UTC, merged