test(e2e): mock all the e2e requests of Next Queries
empathyco/x pull request #85
Opened 2021-08-10 07:13 UTC by CachedaCodes

[EX-4532](https://searchbroker.atlassian.net/browse/EX-4532)

## Motivation and Context ##

After the changes to use a mocked adapter in the Next Queries e2e test we needed to change the e2e test that had Next Queries requests to also use the mocked adapter. This time using dummies instead of stubs.

## How Has This Been Tested? ##

Run the e2e tests and everything should be working as previous but the dummy next queries should be showing in the changed tests

2021-08-10 09:03 UTC, pmareke requested changes

2021-08-10 09:03 UTC, pmareke commented on packages/x-components/tests/e2e/cucumber/next-queries/next-queries.spec.ts
> +// @ts-ignore
Remove these comments please, the `@ts-ignore` is forbidden.

In order to remove the error, you need to change de `tsconfig` file inside the `tests` folder and add the rootDir to the `compilerOptions`.

2021-08-10 10:56 UTC, pmareke requested changes
Please add the `Background` step

2021-08-11 06:11 UTC, pmareke approved these changes

2021-08-11 09:30 UTC, mavmaf approved these changes

2021-08-11 09:52 UTC, merged