fix: number filter schema to map the right values
empathyco/x pull request #861
Opened 2022-11-18 09:06 UTC by tiborux

EX-7442

2022-11-18 09:12 UTC, javieri-empathy requested changes

2022-11-18 09:12 UTC, javieri-empathy commented on packages/x-adapter-platform/src/schemas/models/filters/number-filter.schema.ts
> +      const min = Number(value.split('-')[0]);
Where is the test for this?

2022-11-18 09:14 UTC, tiborux commented on packages/x-adapter-platform/src/schemas/models/filters/number-filter.schema.ts
> +      const min = Number(value.split('-')[0]);
ufff dura esa

2022-11-21 07:17 UTC, annacv commented on packages/x-adapter-platform/src/schemas/models/filters/__tests__/number-filter.spec.ts
> +  it('should map to null the max value even if the max value is 0', () => {
```suggestion
  it('should map to null the max value even if the min value is 0', () => {
```

2022-11-22 12:08 UTC, javieri-empathy approved these changes

2022-11-22 12:11 UTC, annacv approved these changes

2022-11-22 12:23 UTC, merged