chore: Remove unused configs and docs
empathyco/x pull request #873
Opened 2022-11-24 10:22 UTC by javieri-empathy

This configurations now belong to the suggestion components. The recommendations docs where talking about suggestions  (copy & paste :troll:)

2022-11-24 12:34 UTC, tajespasarela submitted a review, later dismissed

2022-11-28 12:55 UTC, mnavarroespinosa requested changes

2022-11-28 12:55 UTC, mnavarroespinosa commented on packages/x-components/src/x-modules/recommendations/components/recommendations.vue
> -### Play with props
I think we could keep this example as `maxItemsToRender` is actually a prop of this component that is even being tested in the tests. 

Apart from changing `BaseSuggestions` to `Recommendations`, the prop `maxItemsToRender` needs to be corrected as it is misspelled as `maxItemToRender` in the example template. It's misspelled also in `PopularSearches`, `BaseSuggestions`, and `NextQueries` files.

2022-11-29 09:11 UTC, tajespasarela submitted a review, later dismissed

2022-11-29 11:13 UTC, tajespasarela approved these changes

2022-11-29 11:14 UTC, merged