docs: update roadmap and customer examples
empathyco/x pull request #900
Opened 2022-12-05 09:48 UTC by herrardo

Update Roadmap and customer examples

# Pull request template
 
Change the Roadmap section to adapt to the current status of the project and anticipate some features.
Change the customers because to be up to date with new customers.

## Motivation and context
Transparency

- [ ] Dependencies. If any, specify:
- [ ] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [x] `Main`
- [ ] Other. Specify:

## How has this been tested?

Tests performed according to [testing guidelines](./contributing/tests.md): 

## Checklist:

- [ ] My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- [ ] I have performed a **self-review** on my own code.
- [ ] I have **commented** my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- [ ] My changes generate **no new warnings**.
- [ ] I have added **tests** that prove my fix is effective or that my feature works.
- [ ] New and existing **unit tests pass locally** with my changes.

2022-12-05 10:46 UTC, javieri-empathy requested changes

2022-12-05 10:46 UTC, javieri-empathy commented on README.md
> +  [animated suggestions](https://docs.empathy.co/develop-empathy-platform/ui-reference/components/search-box/x-components.search-input-placeholder.html)
This does not work on eDocs. Are they already aware?

2022-12-05 10:46 UTC, javieri-empathy commented on README.md
> +- **[Query Results Preview](https://docs.empathy.co/develop-empathy-platform/build-search-ui/web-archetype-integration-guide.html#setting-up-the-queries-preview-dynamically)**:
Link is wrong (and there is a missing `>` in the script of that doc.)
```suggestion
- **[Query Results Preview](https://docs.empathy.co/develop-empathy-platform/build-search-ui/web-archetype-integration-guide.html#dynamic-query-results-preview)**:
```

2022-12-05 13:57 UTC, herrardo commented on README.md
> +  [animated suggestions](https://docs.empathy.co/develop-empathy-platform/ui-reference/components/search-box/x-components.search-input-placeholder.html)
Uhmm..is working as far as i see, could it be something temporal?

2022-12-05 15:21 UTC, herrardo commented on README.md
> +  [animated suggestions](https://docs.empathy.co/develop-empathy-platform/ui-reference/components/search-box/x-components.search-input-placeholder.html)
Yes, the placeholder live example is not working, but it's not relative to this PR. Thanks for the heads up.

2022-12-06 09:48 UTC, javieri-empathy approved these changes

2022-12-06 10:53 UTC, tiborux approved these changes
<img src="https://media3.giphy.com/media/1pA2TskF33668iVDaW/giphy.gif"/>

2022-12-06 10:53 UTC, merged