feat(design-system): modify typography component
empathyco/x pull request #924
Opened 2022-12-14 14:31 UTC by tiborux

EX-7638

2022-12-14 16:22 UTC, mnavarroespinosa requested changes

2022-12-14 16:22 UTC, mnavarroespinosa commented on packages/x-tailwindcss/src/x-tailwind-plugin/components/typography/title1/sizes.ts
>        fontSize: theme('fontSize.xl'),
Check with the design. This should be `xl` or `32px` the values don't match.

2022-12-14 16:22 UTC, mnavarroespinosa commented on packages/x-tailwindcss/src/x-tailwind-plugin/components/typography/title2/sizes.ts
> +      fontSize: theme('fontSize.xl')
Check with the design. This should be `xl` or `20px`, the values don't match.

2022-12-14 16:30 UTC, mnavarroespinosa commented
Is it intended that `Text 1` and `Text 2` are identical, isn't it? Just to double-check.

2022-12-14 21:38 UTC, ajperezbau commented
The `font-weight` of the bold variants seem to be 700 in the designs, but it is set to 600 in the project.

2022-12-14 22:18 UTC, ajperezbau reviewed
Nothing more apart from the things that @mnavarroespinosa commented.
As a side note, I was talking with @javieri-empathy before, and he suggested that maybe in the designs only the tokens should be specified, to avoid confusions with the values and to ease the maintenance of the designs.

2022-12-15 00:18 UTC, tiborux commented
> Nothing more apart from the things that @mnavarroespinosa commented. As a side note, I was talking with @javieri-empathy before, and he suggested that maybe in the designs only the tokens should be specified, to avoid confusions with the values and to ease the maintenance of the designs. It makes sense to me, we can comment it tomorrow with the team if you think alike.

I think it is better, I usually check the token, not the value...

2022-12-15 07:42 UTC, tiborux commented
<img width="505" alt="image" src="https://user-images.githubusercontent.com/6597815/207801313-6cbc1e2e-8569-407b-a7d2-beab7bb975c4.png">

2022-12-15 08:12 UTC, mnavarroespinosa approved these changes
good job!

2022-12-15 08:16 UTC, ajperezbau approved these changes

2022-12-15 09:19 UTC, merged