test: mock popular searches adapter in e2e tests
empathyco/x pull request #93
Opened 2021-08-13 10:10 UTC by mavmaf

EX-4466

## Motivation and Context ##

We needed to have a reliable method of doing e2e tests without relying on APIs outside of our control. This PR implements a version of that solution for the Popular Searches.

- mocked-adapter changed so the getPopularSearches can be intercepted by Cypress
- e2e test for the Popular Searches changed to make use of Cypress' intercept
- Scenario 2 of Popular Searches tests was simplified, together with its .vue, in order to skip checking other components behavior (NQs, RTs, QSs and Results) since it's already being tested in the Search tests (although its refactoring to avoid using the real API is still pending).

## What is the destination branch of this PR? ##

*EX-4466*

## How Has This Been Tested? ##

Run the tests in Cypress to see the intercept working.
In `cypress.json` you can change the testFiles property's first element to `"cucumber/**/*.features"` to be able to select the test to run.

2021-08-13 10:50 UTC, pmareke requested changes
Fix the build and all the errors please.

2021-08-13 10:50 UTC, pmareke commented on packages/x-components/src/__stubs__/suggestions-stubs.factory.ts
> +export function getSuggestionStub(amount = 3): Suggestion[] {
This change from `getSuggestionsStub` to `getSuggestionStub` breaks some tests, please take a look.

2021-08-13 10:50 UTC, pmareke commented on packages/x-components/tests/e2e/cucumber/popular-searches/popular-searches.spec.ts
> +  'the clicked popular search is removed from Popular Searches if hideSessionQueries = {boolean} is true',
Please fix this error

![image](https://user-images.githubusercontent.com/3502075/129346019-a656aa47-9813-4f5a-baf5-1af6d09f1aae.png)

2021-08-17 08:46 UTC, davidmfempathy approved these changes

2021-08-17 08:52 UTC, pmareke requested changes

2021-08-17 08:52 UTC, pmareke commented on packages/x-components/src/__stubs__/suggestions-stubs.factory.ts
> +    modelName: 'PopularSearch',
If we're creating suggestions why are we using always the `PopularSearch` modelName?

2021-08-17 12:48 UTC, pmareke approved these changes

2021-08-17 12:58 UTC, pmareke requested changes

2021-08-17 12:58 UTC, pmareke commented on packages/x-components/tests/e2e/cucumber/empathize.feature
> +    Given a suggestions API
I'm not sure why are we adding this `Given`

2021-08-17 12:58 UTC, pmareke commented on packages/x-components/tests/e2e/cucumber/history-queries.feature
> +    Given a suggestions API
I'm not sure why are we adding this Given

2021-08-17 12:58 UTC, pmareke commented on packages/x-components/tests/e2e/cucumber/search-box.feature
> +    Given a suggestions API
I'm not sure why are we adding this Given

2021-08-17 13:01 UTC, pmareke approved these changes

2021-08-18 06:06 UTC, davidmfempathy approved these changes

2021-08-18 06:07 UTC, merged