feat: Rename lifecycle hook events
empathyco/x pull request #939
Opened 2022-12-19 08:27 UTC by javieri-empathy

This renames the agreed events to match the new shape.

2022-12-19 11:26 UTC, LuisMartinez15 commented
I assume you are only renaming the events that are attached to a vue's lifecycle hook. The `ExtraParamsInitialized` is only emitted when mounting the `ExtraParams` component and, as such, I think it should also be renamed to `ExtraParamsMountedHook`. On a side note, as the component doesn't render anything, can't we move the logic inside the `mounted` hook to the `created` one?

2022-12-19 11:58 UTC, javieri-empathy commented
> I assume you are only renaming the events that are attached to a vue's lifecycle hook. The `ExtraParamsInitialized` is only emitted when mounting the `ExtraParams` component and, as such, I think it should also be renamed to `ExtraParamsMountedHook`. On a side note, as the component doesn't render anything, can't we move the logic inside the `mounted` hook to the `created` one?

I would't rename the `ExtraParamsInitialized`. This is one of the special cases that the team agreed on not renaming (proof below). Moreover, it doesn't mean that all events emitted from a lifecycle hook have to fall under the lifecycle hook category. For instance, DataProvided events.
<img width="314" alt="image" src="https://user-images.githubusercontent.com/68222542/208419039-8ffb1cb7-d2a4-4239-b6b3-d8c7c260a0c4.png">

I agree on moving the mounted -> created hook. I think it works properly. I don't see any duplicated requests, but take a careful second look please.

2022-12-19 12:02 UTC, LuisMartinez15 requested changes
**praise:** thanks for splitting the task in multiple and smaller pull requests ❤️

2022-12-19 12:06 UTC, javieri-empathy commented on packages/x-components/src/x-modules/queries-preview/wiring.ts
> -  QueryPreviewRemoved: {
Yes, there is a task in the backlog for the next sprint about it.

2022-12-19 12:07 UTC, LuisMartinez15 approved these changes
**praise:** good job!

2022-12-20 10:13 UTC, tiborux approved these changes

2022-12-20 10:14 UTC, merged