WIP - [Docs] EX-6046 Add platform-adapter Readme
empathyco/x pull request #968
Opened 2022-12-30 14:07 UTC by annacv

[EX-6046](https://searchbroker.atlassian.net/browse/EX-6046)

WIP - Not ready for review

2023-01-10 15:18 UTC, ajperezbau requested changes
Good job 👌

2023-01-10 16:08 UTC, annacv commented on packages/x-adapter-platform/README.md
> +[snippetConfig.js](https://github.com/empathyco/x-archetype/blob/main/public/snippet-script.js)
Hi @ajperezbau, the intention was to say that if you are not using the archetype, the `extraParams` can be included in the endpoint adapter call (as in the examples), and link to the archetype to show another approach (with the `snippetConfig` file). So I should clarify this a little bit.

2023-01-10 16:13 UTC, annacv commented on packages/x-adapter-platform/README.md
> +The PlatformAdapter instance is a configuration object for each Empathy Platform API’s endpoints:
Cool!

2023-01-10 16:15 UTC, annacv commented on packages/x-adapter-platform/README.md
> +  query: 'trousers',
Yeah, good point!

2023-01-10 16:16 UTC, annacv commented on packages/x-adapter-platform/README.md
> +Search **results**. A search request is triggered when the user has typed or accepted a query. The
Sure, I will rewrite descriptions to make them more agnostic

2023-01-10 16:17 UTC, annacv commented on packages/x-adapter-platform/README.md
> +which contain `add2cart`, `checkout`, `click`, `query` and `wishlist` actions.
and the documentation will be easier to maintain, as we won't need to be updating in case this event's list changes ;P

2023-01-12 16:51 UTC, ajperezbau submitted a review, later dismissed
Nice 😎

2023-01-18 10:05 UTC, LuisMartinez15 requested changes
**praise**: good job  👏🏿

2023-01-18 10:05 UTC, LuisMartinez15 commented on packages/x-adapter-platform/README.md
>  To start contributing to the project, please take a look to our
```suggestion
To start contributing to the project, please take a look at our
```

2023-01-18 10:05 UTC, LuisMartinez15 commented on packages/x-adapter-platform/README.md
> +so we recommend you check it out.
```suggestion
so we recommend you to check it out.
```

2023-01-18 10:20 UTC, annacv commented on packages/x-adapter-platform/README.md
> +<br>
Oh noooooo, I could "convince" @ajperezbau that it was a design thing to reinforce sections separation and improve legibility. Wouldn't you buy that argument @LuisMartinez15 ?? 😁

2023-01-18 10:29 UTC, annacv commented
So let me know what do you think about `<br>` @LuisMartinez15 . If we remove them from here, I'll do so on` x-adapter` readme.
Whatever it is I will apply some spelling suggestions that you made here in the `x-adapter` readme.

2023-01-18 10:37 UTC, LuisMartinez15 commented on packages/x-adapter-platform/README.md
> +<br>
😅 

In my opinion, people are already used to read markdown files with their standard format. Adding `<br>` shouldn't be needed at all and I'm not so sure that it improves legibility. Anyway, if you want to do the experiment of sharing this file with a non-technical person, with and without those tags, to see their feedback, go ahead.

2023-01-18 10:50 UTC, annacv commented on packages/x-adapter-platform/README.md
> +<br>
🎊😁

2023-01-18 10:53 UTC, LuisMartinez15 submitted a review, later dismissed

2023-01-18 11:08 UTC, ajperezbau approved these changes

2023-01-18 11:26 UTC, LuisMartinez15 approved these changes

2023-01-18 11:27 UTC, merged