feat: improve types
empathyco/x pull request #992
Opened 2023-01-09 22:44 UTC by LuisMartinez15

EX-7789

2023-01-10 08:08 UTC, tiborux commented on packages/x-priority-queue/src/x-priority-queue.types.ts
> + * Adsadsadas.
Fix this comment

2023-01-10 08:16 UTC, tiborux commented on packages/x-priority-queue/src/x-priority-queue.ts
> +  public get keys(): SomeKey[] {
In the constructor, change the type to be `(a: number, b: number) => boolean`

2023-01-10 08:35 UTC, tiborux commented on packages/x-priority-queue/src/x-priority-queue.ts
> +   * See {@link XPriorityQueue.(push:1)}
Can we use just {@link XPriorityQueue.push} I dont know if it works.

2023-01-10 08:38 UTC, tiborux commented on packages/x-priority-queue/src/x-priority-queue.ts
> +export class BaseXPriorityQueueNode<
`priority number and data record.`

2023-01-11 10:48 UTC, CachedaCodes requested changes

2023-01-11 15:12 UTC, CachedaCodes approved these changes

2023-01-12 09:21 UTC, tiborux approved these changes

2023-01-12 09:23 UTC, merged