feat: have importable home template from x-archetype-utils
empathyco/x pull request #994
Opened 2023-01-10 11:28 UTC by CachedaCodes

[EX-7633](https://searchbroker.atlassian.net/browse/EX-7633)

## Motivation and context
We wanted to have a home template to embed in the demo envs of the archetype and the clients.
The designs for the home template were replicated with the SVGs directly in the page for simplicity when importing it. I decided to get rid of the GIF for now because it was a 9 MB file that would be a pain to import and didn't seem worth it to add at this stage.

- [ ] Dependencies. If any, specify:
- [ X ] Open issue. If applicable, link:

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ X ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Change requires a documentation update

## What is the destination branch of this PR?

- [ X ] `Main`
- [ ] Other. Specify:

## How has this been tested?

Wrap the html in `home-template.html` in `<html><body></body></html>` to see how it would look when embedded in a `body` and test the dependency locally to check that nothing was broken with the change to Rollup.

2023-01-10 12:06 UTC, herrardo commented on packages/x-archetype-utils/src/home/home-template.html
> +          <svg
This SVG with the circle should be paired with` Built on open-source technology` element, it was wrong in design.

![image](https://user-images.githubusercontent.com/4663897/211547404-56e70723-3251-4683-859a-59876de7a09f.png)

2023-01-10 12:23 UTC, herrardo requested changes

2023-01-10 12:23 UTC, herrardo commented on packages/x-archetype-utils/src/home/home-template.html
> +          . Just load the Archetype JS file and initialise it!
```suggestion
         . Just load the Archetype JS file and initialise it!
```

2023-01-10 12:23 UTC, herrardo commented on packages/x-archetype-utils/src/home/home-template.html
> +          <p class="x-archetype-section3__title">Built on open-source technology</p>
```suggestion
          <p class="x-archetype-section3__title">
            <a
              href="https://github.com/empathyco/x"
              target="_blank"
            >
              Built on open-source technology
            </a>
          </p>
```

2023-01-10 12:23 UTC, herrardo commented on packages/x-archetype-utils/src/home/home-template.html
> +          <p class="x-archetype-section3__title">Interoperable: Works with any API!</p>
```suggestion
          <p class="x-archetype-section3__title">
            <a
              href="https://docs.empathy.co/video-library.html?video=zNq3n_3HA2I"
              target="_blank"
            >
              Interoperable: Works with any API!
            </a>
          </p>
```

2023-01-10 12:36 UTC, herrardo approved these changes

2023-01-10 14:59 UTC, LuisMartinez15 submitted a review, later dismissed
**praise:** good job! 👏🏿

2023-01-10 14:59 UTC, LuisMartinez15 commented on packages/x-archetype-utils/package.json
>      "concurrently": "~7.6.0",
**nitpick:** remove unused `concurrently` package

```suggestion
```

2023-01-10 14:59 UTC, LuisMartinez15 commented on packages/x-archetype-utils/rollup.config.js
> +import copy from 'rollup-plugin-copy';
**nitpick**: order `imports` alphabetically

```suggestion
import copy from 'rollup-plugin-copy';
import del from 'rollup-plugin-delete';
import typescript from 'rollup-plugin-typescript2';
```

2023-01-10 14:59 UTC, tiborux commented on packages/x-archetype-utils/src/home/home-template.html
> +  .x-archetype-header,
```suggestion
```

2023-01-11 07:44 UTC, LuisMartinez15 approved these changes

2023-01-11 07:50 UTC, tiborux commented on packages/x-archetype-utils/package.json
> +    "rollup-plugin-copy": "~3.4.0",
add these dependencies:

```suggestion
    "rollup-plugin-copy": "~3.4.0",
    "rollup-plugin-delete": "~2.0.0",
    "rollup-plugin-typescript2": "~0.34.1",
```

2023-01-11 08:12 UTC, LuisMartinez15 requested changes
see beltran's comment regarding missing dependencies

2023-01-11 08:17 UTC, herrardo submitted a review, later dismissed

2023-01-11 08:26 UTC, tiborux commented
in mobile:

there is no space above text:

![image](https://user-images.githubusercontent.com/6597815/211755338-a29fc465-953d-4ad4-a5e4-c91a02acb444.png)

to much space between the line and the searchbox:

![image](https://user-images.githubusercontent.com/6597815/211755386-7b2524fd-875c-4bc3-a881-9bff4e65d7a6.png)

2023-01-11 08:31 UTC, LuisMartinez15 submitted a review, later dismissed

2023-01-11 08:33 UTC, LuisMartinez15 approved these changes

2023-01-11 08:48 UTC, merged